Repository Skyscanner/backpack-ios, pull requests merged in 2022-06, with the labels that each got.

#1318 KOA-4971 Horizontal navigation typography fix
  Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationTypes.swift
Labels: minor

#1332 KOA-5168 add environment to build step when releasing
  .github/workflows/release.yml
Labels: patch

#1333 KOA-5168 move docs publish step
  .github/workflows/_build.yml
  .github/workflows/release.yml
Labels: patch

#1334 Update release.yml
  .github/workflows/release.yml
Labels: patch

#1335 KOA-5168 Install cocoapods from bundle
  .github/workflows/release.yml
Labels: skip-changelog

#1326 Chip component update
  Backpack/Chip/Classes/BPKChip.swift
  Backpack/Chip/Classes/BPKChipColors.swift
  Backpack/Chip/Classes/BPKChipStyle.swift
  Backpack/Chip/Classes/BPKChipType.swift
  Example/Backpack NativeUITests/ChipUITest.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Chip/ChipPreviewCollectionViewCell.swift
  Example/Backpack/UIKit/Components/Chip/ChipSelectorViewController.swift
  Example/Backpack/UIKit/Components/Chip/ChipsViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/ChipGroups.swift
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipDisabledUnselectedWithIcon_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipDisabledUnselectedWithIcon_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipDisabled_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipDisabled_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedHighlighted_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedHighlighted_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedThemed_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedThemed_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedWithIcon_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelectedWithIcon_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledSelected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselectedHighlighted_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselectedHighlighted_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselectedWithIcon_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselectedWithIcon_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipEnabledUnselected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipFilledSelected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipFilledSelected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipFilledUnselected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipFilledUnselected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipWithCustomBackgroundColorSelected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipWithCustomBackgroundColorSelected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipWithCustomBackgroundColorUnselected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/BPKChipSnapshotTest/testChipWithCustomBackgroundColorUnselected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipDisabled_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipDisabled_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipSelectedWithIcon_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipSelectedWithIcon_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipSelected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipSelected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipUnselected_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipUnselected_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithDismissType_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithDismissType_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithIcon_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithIcon_light_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithSelectType_dark_mode@2x.png
  Example/BackpackTests/ReferenceImages_64/Backpack_SnapshotTests.BPKChipSnapshotTest/testChipWithSelectType_light_mode@2x.png
  Example/SnapshotTests/BPKChipSnapshotTest.m
  Example/SnapshotTests/BPKChipSnapshotTest.swift
  UNRELEASED.md
Labels: minor

#1338 KOA-5169 clean rakefile
  .github/workflows/_build.yml
  ARCHITECTURE.md
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  Rakefile
  scripts/build-docs-ci
  scripts/ci
  scripts/create-docs-header
  scripts/lint
  scripts/take-screenshots
Labels: skip-changelog

#1324 KOA-4949 Update FloatingPanel from 1.6.6 to 2.5.2
  Backpack.podspec
  Backpack/BottomSheet/Classes/BPKFloatingPanelPosition.swift
  Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
  Backpack/BottomSheet/Classes/BottomSheet.swift
  Backpack/BottomSheet/Classes/BottomSheetInsets.swift
  Backpack/BottomSheet/Classes/IntrinsicBottomSheetLayout.swift
  Backpack/BottomSheet/Classes/ModalBottomSheetLayout.swift
  Backpack/BottomSheet/Classes/PersistentBottomSheetLayout.swift
  Example/Backpack/UIKit/Components/Bottom Sheet/BottomSheet.storyboard
  Example/Podfile.lock
  UNRELEASED.md
Labels: major

#1343 pod installing before building uikit
  .github/workflows/_build-docs.yml
  .github/workflows/_build.yml
  scripts/lint
Labels: skip-changelog

#1323 OGM-529 Can select whole month from a button in the Calendar
  .github/workflows/_build.yml
  Backpack/Calendar/Classes/BPKCalendar.h
  Backpack/Calendar/Classes/BPKCalendar.m
  Backpack/Calendar/Classes/BPKCalendarCell.h
  Backpack/Calendar/Classes/BPKCalendarCell.m
  Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.h
  Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.m
  Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.h
  Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.m
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.h
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.m
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.h
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.m
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.h
  Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.m
  Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
  Backpack/Calendar/Classes/Calendar.h
  Example/Backpack NativeUITests/CalendarUITest.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Calendar/CalendarViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/CalendarGroups.swift
  Example/BackpackTests/ReferenceImages_64/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton@2x.png
  Example/SnapshotTests/BPKCalendarSnapshotTest.m
  Example/Tests/BPKCalendarMonthDateProviderTests.swift
Labels: major

#1348 No jira fixing docs deployment release
  .github/workflows/release.yml
Labels: skip-changelog

#1350 building and deploying docs as part of pod deployment
  .github/workflows/release.yml
Labels: skip-changelog

#1352 No jira project cleanup
  .github/dependabot.yml
  .github/release-drafter.yml
  Example/.idea/vcs.xml
  Example/.swiftlint.yml
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/Backpack Native-Bridging-Header.h
  Example/Backpack/UIKit/Components/Button/BPKButtonsViewController.m
  Example/Backpack/UIKit/Components/Link/TappableLinkLabelsViewController.swift
  Example/Backpack/Utils/BPKExampleAppTitleAttributes.h
  Example/Backpack/Utils/BPKExampleAppTitleAttributes.m
  Example/SnapshotTests/Utils/BPKIconsTestsUtils.m
  migration-guides/42.0.0-migration-guide.md
  migration-guides/horizontal-nav-migration-guide.md
  migration-guides/icon-migration-guide.md
  scripts/ci
  scripts/gulp/generation/uikit/icons.js
  templates/icons/BPKIconsExampleTestsUtil.njk
Labels: skip-changelog

#1355 KOA-5072 Add BPKBadge to SwiftUI
  Backpack-SwiftUI/Badge/Classes/BPKBadge+Style.swift
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Badge/Classes/BPKBadgeStyle.swift
  Backpack-SwiftUI/Badge/README.md
  Backpack-SwiftUI/Tests/Badge/BPKBadgeTests.swift
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.rtl.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.rtl.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.rtl.png
  Example/Backpack Screenshot/BackpackSnapshotTestCase.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Badge/BadgeExampleVIew.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  screenshots/iPhone 8-badge___all_dm.png
  screenshots/iPhone 8-badge___all_lm.png
  screenshots/iPhone 8-swiftui_badge___default_dm.png
  screenshots/iPhone 8-swiftui_badge___default_lm.png
Labels: swiftui, minor

#1358 Fix BPKBottomSheet
  Backpack.podspec
  Backpack/BottomSheet/Classes/BottomSheet.swift
  Backpack/BottomSheet/README.md
  Backpack/Tests/SnapshotTests/BottomSheet/BPKBottomSheetTest.swift
  Backpack/Tests/SnapshotTests/BottomSheet/Helpers/BottomSheetTestListViewController.swift
  Backpack/Tests/SnapshotTests/BottomSheet/Helpers/BottomSheetTestViewController.swift
  Backpack/Tests/SnapshotTests/BottomSheet/__Snapshots__/BPKBottomSheetTest/test_moveBottomSheet_toFull.1.png
  Backpack/Tests/SnapshotTests/BottomSheet/__Snapshots__/BPKBottomSheetTest/test_moveBottomSheet_toHalf.1.png
  Backpack/Tests/SnapshotTests/BottomSheet/__Snapshots__/BPKBottomSheetTest/test_moveBottomSheet_toTip.1.png
  Example/Podfile.lock
Labels: patch
