Repository Skyscanner/backpack-ios, pull requests merged in 2022-09, with the labels that each got.

#1415 KOA-5571 star rating semantic color
  Backpack/StarRating/Classes/BPKStar.m
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKStarRatingSnapshotTest/testStarRatingSizesRatingsAndRoundings_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKStarRatingSnapshotTest/testStarRatingSizesRatingsAndRoundings_light_mode@2x.png
  screenshots/iPhone 8-skeleton___all_dm.png
  screenshots/iPhone 8-skeleton___all_lm.png
  screenshots/iPhone 8-star-rating___docs_dm.png
  screenshots/iPhone 8-star-rating___docs_lm.png
Labels: minor

#1416 KOA-5572 BPKSwitch semantic colours
  Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift
  Backpack/Switch/Classes/BPKSwitch.m
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOff_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOff_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOnWithTheme_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOnWithTheme_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOn_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSwitchSnapshotTest/testSwitchWhenOn_light_mode@2x.png
  screenshots/iPhone 8-swiftui_switch___default_dm.png
  screenshots/iPhone 8-swiftui_switch___default_lm.png
  screenshots/iPhone 8-switch___default_dm.png
  screenshots/iPhone 8-switch___default_lm.png
  scripts/take-screenshots
Labels: minor

#1419 KOA-5570 BPKSpinner semantic color
  Backpack-SwiftUI/Spinner/Classes/BPKSpinner+Style.swift
  Backpack-SwiftUI/Tests/Spinner/__Snapshots__/BPKSpinnerTests/test_allSpinnerStyles.dark-mode.png
  Backpack/Spinner/Classes/BPKSpinner.h
  Backpack/Spinner/Classes/BPKSpinner.m
  Backpack/Spinner/README.md
  Backpack/Tests/SnapshotTests/BPKSpinnerSnapshotTest.m
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKSpinnerSnapshotTest/testSpinnersWithTheme_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKSpinnerSnapshotTest/testSpinnersWithTheme_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKSpinnerSnapshotTest/testSpinners_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKSpinnerSnapshotTest/testSpinners_light_mode@2x.png
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Spinner/Spinners.storyboard
  Example/Backpack/UIKit/Components/Spinner/SpinnersViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone 8-spinner___all_dm.png
  screenshots/iPhone 8-spinner___all_lm.png
  screenshots/iPhone 8-swiftui_spinner___default_dm.png
Labels: minor

#1420 [BPKSkeleton] Add removeShimmer method and update bodytext's size.
  Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton+Size.swift
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithShimmer.dark-mode.png
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithShimmer.light-mode.png
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithShimmer.rtl.png
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithoutShimmer.dark-mode.png
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithoutShimmer.light-mode.png
  Backpack-SwiftUI/Tests/Skeleton/__Snapshots__/BPKSkeletonTests/test_allSkeletonsWithoutShimmer.rtl.png
  Backpack/Skeleton/Classes/BPKSkeleton.swift
  Backpack/Skeleton/Classes/BPKSkeletonSize.swift
  Backpack/Skeleton/Classes/BPKTextSkeleton.swift
  Backpack/Skeleton/README.md
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testBodytextSkeleton_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testBodytextSkeleton_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testCustomSizeBodytextSkeleton_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testCustomSizeBodytextSkeleton_light_mode@2x.png
  screenshots/iPhone 8-skeleton___all_dm.png
  screenshots/iPhone 8-skeleton___all_lm.png
Labels: minor

#1422 Update BPSkeleton demo view
  Backpack-SwiftUI/Skeleton/README.md
  Backpack/Skeleton/Classes/BPKSkeleton.swift
  Backpack/Skeleton/README.md
  Example/Backpack/SwiftUI/Components/Skeleton/SkeletonExampleView.swift
  Example/Backpack/UIKit/Components/Skeleton/SkeletonViewController.swift
  screenshots/iPhone 8-skeleton___all_dm.png
  screenshots/iPhone 8-skeleton___all_lm.png
  screenshots/iPhone 8-swiftui_skeleton___default_dm.png
  screenshots/iPhone 8-swiftui_skeleton___default_lm.png
Labels: minor

#1426 KOA-5567 Dialog semantic color
  Backpack/Dialog/Classes/BPKDialogController.m
  Backpack/Dialog/Classes/BPKDialogIconView.m
  Backpack/Dialog/Classes/BPKDialogView.m
  Backpack/Tests/SnapshotTests/BPKDialogViewSnapshotTest.swift
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testChangingIconDefinitionAfterPresenting_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewNoButtons_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithButtons_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithLargeCornerStyleAndFlareViewAndButtons_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithLargeCornerStyleAndFlareViewAndSmallButtons_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithLargeCornerStyleAndTallFlareViewAndButtons_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithNoIconAndNoTitle_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKDialogViewSnapshotTest/testDialogViewWithNoIcon_light_mode@2x.png
Labels: minor

#1429 KOA-5482 Update BarChart to semantic colours
  Backpack/BarChart/Classes/BarChart.swift
  Backpack/BarChart/Classes/BarChartBar.swift
  Backpack/BarChart/Classes/BarChartCollectionView.swift
  Backpack/BarChart/Classes/MiniFlareView.swift
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultSelected_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultSelected_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueDescription_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueDescription_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueRealSelected_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueRealSelected_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueSelected_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValueSelected_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValue_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefaultWithValue_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefault_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartBarSnapshotTest/testBarDefault_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartSnapshotTest/testBarChartDefaultSelected_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartSnapshotTest/testBarChartDefaultSelected_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartSnapshotTest/testBarChartDefault_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKBarChartSnapshotTest/testBarChartDefault_light_mode@2x.png
  screenshots/iPhone 8-bar-chart___default_dm.png
  screenshots/iPhone 8-bar-chart___default_lm.png
Labels: minor, colour

#1438 BPKSkeleton semantic colours
  Backpack-SwiftUI/Skeleton/Classes/BPKShimmer.swift
  Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton.swift
  Backpack/Skeleton/Classes/BPKShimmerLayer.swift
  Backpack/Skeleton/Classes/BPKShimmerOverlayView.swift
  Backpack/Skeleton/Classes/BPKSkeleton.swift
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testShimmerSkeleton_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/Backpack_Unit_SnapshotTests.BPKSkeletonSnapshotTest/testShimmerSkeleton_light_mode@2x.png
  screenshots/iPhone 8-skeleton___all_dm.png
  screenshots/iPhone 8-skeleton___all_lm.png
Labels: minor

#1439 New Colour demo screen
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Tokens/ColorChipView.swift
  Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
  Example/Backpack/UIKit/Tokens/ColorPreviewCollectionViewCell.swift
  Example/Backpack/UIKit/Tokens/ColorsViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/CardGroups.swift
  Example/Backpack/Utils/FeatureStories/TokenCells.swift
  Example/Backpack/Utils/ThemeRegistry.swift
Labels: skip-changelog
