Repository Skyscanner/backpack-ios, pull requests merged in 2022-10, with the labels that each got.

#1456 Update canvasContrast and new icons
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-lg.imageset/baggage-cabin-add-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-sm.imageset/baggage-cabin-add-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-lg.imageset/baggage-cabin-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-lg.imageset/baggage-cabin-not-included-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-sm.imageset/baggage-cabin-not-included-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-sm.imageset/baggage-cabin-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-lg.imageset/baggage-checked-add-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-sm.imageset/baggage-checked-add-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-lg.imageset/baggage-checked-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-lg.imageset/baggage-checked-not-included-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-sm.imageset/baggage-checked-not-included-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-sm.imageset/baggage-checked-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-lg.imageset/baggage-generic-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-sm.imageset/baggage-generic-sm.svg
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  Backpack-SwiftUI/Tests/Icons/Generated/IconsTestsUtils.swift
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.rtl.png
  Backpack/Color/Classes/Generated/BPKColor.h
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/Color/Classes/Generated/UIColor+Backpack.h
  Backpack/Icon/Classes/Generated/BPKIconNames.h
  Backpack/Icon/Classes/Generated/BPKIconNames.m
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.h
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.m
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.h
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.m
  Backpack/Tests/SnapshotTests/MapAnnotation/BPKMapAnnotationSnapshotTest.swift
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKIconSnapshotTest/testAllLargeIcons@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKIconSnapshotTest/testAllSmallIcons@2x.png
  Backpack/Tests/SnapshotTests/Utils/BPKIconsTestsUtils.m
  Example/Backpack/SwiftUI/Components/Icons/Generated/BPKIconsExampleUtil.swift
  package-lock.json
  package.json
  screenshots/iPhone 8-icon___all_dm.png
  screenshots/iPhone 8-icon___all_lm.png
Labels: minor

#1455 Added solid line style for BPKDivider
  Backpack/Card/Classes/BPKCardDivider.h
  Backpack/Card/Classes/BPKCardDivider.m
  Backpack/Card/Classes/BPKCardDividerLineStyleValues.h
  Backpack/Card/Classes/BPKCardDividerLineStyleValues.m
  Backpack/Card/Classes/BPKDividedCard.h
  Backpack/Card/Classes/BPKDividedCard.m
  Backpack/Tests/SnapshotTests/BPKCardSnapshotTest.m
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKCardSnapshotTest/testDividedSnapshotVerticalSolidLineWithouPadding_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKCardSnapshotTest/testDividedSnapshotVerticalSolidLineWithouPadding_light_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKCardSnapshotTest/testDividedSnapshotVerticalSolidLine_dark_mode@2x.png
  Backpack/Tests/SnapshotTests/ReferenceImages_64/BPKCardSnapshotTest/testDividedSnapshotVerticalSolidLine_light_mode@2x.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack/UIKit/Components/Card/DividedCardsViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/CardGroups.swift
  screenshots/iPhone 8-card___with-solid-divider-with-padding_dm.png
  screenshots/iPhone 8-card___with-solid-divider-with-padding_lm.png
  screenshots/iPhone 8-card___with-solid-divider-without-padding_dm.png
  screenshots/iPhone 8-card___with-solid-divider-without-padding_lm.png
Labels: minor

#1457 SwiftUI BPKIconView improved API
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
Labels: minor

#1459 [KOA-5373] assertSnapshot helper function to use in all tests
  Backpack/Tests/SnapshotTests/Utils/AssertSnapshot.swift
Labels: minor

#1466 Update surface contrast colour
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack/Color/Classes/Generated/BPKColor.h
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/Color/Classes/Generated/UIColor+Backpack.h
  package-lock.json
  package.json
Labels: patch

#1467 [KOA5645] Copying docs to latest folder
  scripts/build-docs
Labels: patch

#1470 Update docs with shields (reference + Github link)
  Backpack-SwiftUI/Badge/README.md
  Backpack-SwiftUI/Button/README.md
  Backpack-SwiftUI/Card/README.md
  Backpack-SwiftUI/Skeleton/README.md
  Backpack-SwiftUI/Spinner/README.md
  Backpack-SwiftUI/Switch/README.md
  Backpack-SwiftUI/Text/README.md
  Backpack/Badge/README.md
  Backpack/BarChart/README.md
  Backpack/BottomSheet/README.md
  Backpack/Button/README.md
  Backpack/Calendar/README.md
  Backpack/Card/README.md
  Backpack/Chip/README.md
  Backpack/Dialog/README.md
  Backpack/FlareView/README.md
  Backpack/HorizontalNavigation/README.md
  Backpack/Icon/README.md
  Backpack/Label/README.md
  Backpack/Map/README.md
  Backpack/NavigationBar/README.md
  Backpack/Nudger/README.md
  Backpack/OverlayView/README.md
  Backpack/Panel/README.md
  Backpack/ProgressBar/README.md
  Backpack/Rating/README.md
  Backpack/Skeleton/README.md
  Backpack/Snackbar/README.md
  Backpack/Spinner/README.md
  Backpack/StarRating/README.md
  Backpack/Switch/README.md
  Backpack/TappableLinkLabel/README.md
  Backpack/TextField/README.md
  Backpack/TextView/README.md
  Backpack/Toast/README.md
Labels: skip-changelog

#1469 [KOA-5123] Example for tokens
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Tokens/RadiusTokensView.swift
  Example/Backpack/SwiftUI/Tokens/SpacingTokensView.swift
  Example/Backpack/UIKit/Tokens/ColorTokensViewController.swift
  Example/Backpack/UIKit/Tokens/RadiusTokensViewController.swift
  Example/Backpack/UIKit/Tokens/SpacingTokensViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/ButtonGroups.swift
  Example/Backpack/Utils/FeatureStories/TokenCells.swift
Labels: patch

#1471 Update readme with smaller images
  Backpack-SwiftUI/Badge/README.md
  Backpack-SwiftUI/Button/README.md
  Backpack-SwiftUI/Card/README.md
  Backpack-SwiftUI/Skeleton/README.md
  Backpack-SwiftUI/Spinner/README.md
  Backpack-SwiftUI/Switch/README.md
  Backpack-SwiftUI/Text/README.md
  Backpack/BarChart/README.md
  Backpack/BottomSheet/README.md
  Backpack/Button/README.md
  Backpack/Calendar/README.md
  Backpack/Card/README.md
  Backpack/Chip/README.md
  Backpack/Dialog/README.md
  Backpack/FlareView/README.md
  Backpack/HorizontalNavigation/README.md
  Backpack/Icon/README.md
  Backpack/Label/README.md
  Backpack/Map/README.md
  Backpack/NavigationBar/README.md
  Backpack/Nudger/README.md
  Backpack/OverlayView/README.md
  Backpack/Panel/README.md
  Backpack/ProgressBar/README.md
  Backpack/Rating/README.md
  Backpack/Skeleton/README.md
  Backpack/Snackbar/README.md
  Backpack/Spinner/README.md
  Backpack/StarRating/README.md
  Backpack/Switch/README.md
  Backpack/TappableLinkLabel/README.md
  Backpack/TextField/README.md
  Backpack/TextView/README.md
  Backpack/Toast/README.md
Labels: skip-changelog
