Repository Skyscanner/backpack-ios, pull requests merged in 2023-06, with the labels that each got.

#1669 Setting BPKFlightLeg imageView contentMode to aspectFit
  Backpack/FlightLeg/Classes/BPKFlightLeg.swift
Labels: minor

#1671 Update Skeleton SwiftUI screenshots
  screenshots/iPhone-swiftui_skeleton___default_dm.png
  screenshots/iPhone-swiftui_skeleton___default_lm.png
Labels: skip-changelog

#1674 BPKHotelStarRating UIKit
  Backpack/StarRating/Classes/BPKHotelStarRating.swift
  Backpack/StarRating/README.md
  Backpack/Tests/SnapshotTests/BPKHotelStarRatingSnapshotTests.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKHotelStarRatingSnapshotTests/testHotelStarRatingSizesAndRatings.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKHotelStarRatingSnapshotTests/testHotelStarRatingSizesAndRatings.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKHotelStarRatingSnapshotTests/testHotelStarRatingSizesAndRatings.rtl.png
  Example/Backpack/UIKit/Components/Star rating/StarRatings.storyboard
  Example/Backpack/UIKit/Components/Star rating/StarRatingsDocViewController.swift
  screenshots/iPhone-star-rating___docs_dm.png
  screenshots/iPhone-star-rating___docs_lm.png
Labels: minor

#1677 NOJIRA: update card button's circle color to white50 & black50
  Backpack/CardButton/Classes/CardButtonBackgroundView.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testCheckedSaveCardButtonSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testUncheckedSaveCardButtonSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKShareCardButtonSnapshotTest/testShareCardButtonSnapshot.dark-mode.png
  screenshots/iPhone-card-button___all_dm.png
  screenshots/iPhone-card-button___all_lm.png
Labels: minor

#1684 Podfile changes
  Backpack-SwiftUI.podspec
  Example/Podfile
  Example/Podfile.lock
Labels: skip-changelog

#1683 KOA-5976 Dynamic type util
  Backpack-SwiftUI/Utils/Classes/View+SizeCategory.swift
Labels: skip-changelog, Accessibility

#1679 [LMN-149] Single select chips group
  Backpack-SwiftUI/ChipGroup/Classes/BPKChipGroupType.swift
  Backpack-SwiftUI/ChipGroup/Classes/BPKSingleSelectChipGroup.swift
  Backpack-SwiftUI/ChipGroup/README.md
  Backpack-SwiftUI/Tests/ChipGroup/BPKChipGroupTests.swift
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_railChips_default.dark-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_railChips_default.light-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_railChips_default.rtl.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_wrapChips_onDark.dark-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_wrapChips_onDark.light-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_singleSelect_wrapChips_onDark.rtl.png
  Backpack-SwiftUI/Utils/Classes/FlowStackView.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectRailExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectWrapExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/ChipGroupProvider.swift
  screenshots/iPhone-swiftui_chip-group___rail_dm.png
  screenshots/iPhone-swiftui_chip-group___rail_lm.png
  screenshots/iPhone-swiftui_chip-group___wrap_dm.png
  screenshots/iPhone-swiftui_chip-group___wrap_lm.png
Labels: minor
