Repository Skyscanner/backpack-ios, pull requests merged in 2023-10, with the labels that each got.

#1791 Added Label Flares to BPKRangeSlider
  Backpack-SwiftUI/MapMarker/Classes/BPKPriceMapMarker+Shape.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPriceMapMarker.swift
  Backpack-SwiftUI/Slider/Classes/BPKRangeSlider.swift
  Backpack-SwiftUI/Slider/README.md
  Backpack-SwiftUI/Tests/Slider/SliderTests.swift
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.dark-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.light-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.rtl.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSliderWithThumbnailLabels.dark-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSliderWithThumbnailLabels.light-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSliderWithThumbnailLabels.rtl.png
  Backpack-SwiftUI/Utils/Classes/BPKLabelFlareShape.swift
  Example/Backpack/SwiftUI/Components/Slider/SliderExampleView.swift
  screenshots/iPhone-swiftui_slider___all_dm.png
  screenshots/iPhone-swiftui_slider___all_lm.png
Labels: swiftui, minor

#1793 UIKit Dynamic type
  Backpack/Font/Classes/BPKFontManager.m
  Backpack/Font/Classes/Generated/BPKFont.h
  Backpack/Font/Classes/Generated/BPKFont.m
  Backpack/Label/Classes/BPKLabel.m
  Example/Backpack/AppDelegate.swift
  Example/Podfile.lock
  templates/BPKFont.h.njk
  templates/BPKFont.m.njk
Labels: patch, Accessibility, DynamicType

#1794 [BugFix] DynamicType and AttributedText
  Backpack/Font/Classes/Generated/BPKFont.m
  Backpack/Label/Classes/BPKLabel.m
  templates/BPKFont.m.njk
Labels: patch

#1795 [DynamicType] BPKChip
  Backpack/Chip/Classes/BPKChip.swift
  Example/Backpack/UIKit/Components/Chip/ChipsViewController.swift
Labels: minor, Accessibility, DynamicType
