Repository Skyscanner/backpack-ios, pull requests merged in 2023-01, with the labels that each got.

#1530 [KOA-5813] Introducing Brand Badge
  Backpack-SwiftUI/Badge/Classes/BPKBadge+Style.swift
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Badge/Classes/BPKBadgeStyle.swift
  Backpack-SwiftUI/Tests/Badge/BPKBadgeTests.swift
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithIcon.rtl.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_allBadgesWithoutIcon.rtl.png
  Backpack/Badge/Classes/Badge.swift
  Backpack/Badge/Classes/BadgeType.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Badge/BadgeExampleVIew.swift
  Example/Backpack/UIKit/Components/Badge/BPKBadgeContainer.swift
  Example/Backpack/UIKit/Components/Badge/Badges.storyboard
  Example/Backpack/UIKit/Components/Badge/BadgesViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
Labels: major

#1532 [KOA-5815] Removing trailing icon
  Backpack/Badge/Classes/Badge.swift
  Backpack/Badge/Classes/BadgeIcon.swift
  Example/Backpack/UIKit/Components/Badge/BadgesViewController.swift
Labels: major

#1538 [KOA-5839] Removing pill radii
  Backpack-SwiftUI/Radii/Classes/Generated/BPKRadii.swift
  Backpack-SwiftUI/Tests/Radii/RadiiTests.swift
  Backpack/Radii/Classes/Generated/BPKRadii.h
  Backpack/Radii/Classes/Generated/BPKRadii.m
  Backpack/Tests/UnitTests/BPKRadiiTest.m
  Example/Backpack/SwiftUI/Tokens/RadiusTokensView.swift
  Example/Backpack/UIKit/Tokens/RadiusTokensViewController.swift
  package-lock.json
  package.json
Labels: major

#1542 Fix SwiftUI previews (in pod)
  Example/Podfile
  Example/Podfile.lock
Labels: skip-changelog

#1541 Add elevation property for BpkDividedCard SwiftUI version
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
  Backpack-SwiftUI/Card/Classes/BPKCardElevation.swift
  Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
  Backpack-SwiftUI/Card/README.md
  Backpack-SwiftUI/Tests/Card/BPKDividedCardTests.swift
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardDefault.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardDefault.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardDefault.rtl.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardOnFocused.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardOnFocused.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardOnFocused.rtl.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithPaddedContent.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithPaddedContent.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithPaddedContent.rtl.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithoutElevation.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithoutElevation.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/BPKDividedCardTests/testDividedCardWithoutElevation.rtl.png
  Example/Backpack/SwiftUI/Components/Card/DividedCardExampleView.swift
  screenshots/iPhone 8-swiftui_divided-card___default_dm.png
Labels: swiftui, minor
