Repository Skyscanner/backpack-ios, pull requests merged in 2023-03, with the labels that each got.

#1586 BPKFloatingNotification layout improvement
  Backpack/FloatingNotification/Classes/BPKFloatingNotification.swift
  Backpack/FloatingNotification/Classes/FloatingNotificationAnimator.swift
  Backpack/FloatingNotification/Classes/FloatingNotificationView.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustTextForiPad.rtl.png
Labels: minor

#1587 KOA-5907 BPKLabel documentation update
  Backpack/Label/README.md
  Example/Backpack Screenshot/BackpackSnapshotTestCase.swift
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Text/LabelMultiFontStyleViewController.swift
  Example/Backpack/UIKit/Components/Text/LabelViewController.swift
  Example/Backpack/UIKit/Components/Text/Labels.storyboard
  Example/Backpack/UIKit/Components/Text/LabelsPerformanceViewController.swift
  Example/Backpack/UIKit/Components/Text/LabelsViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/LabelGroups.swift
  Example/Podfile.lock
  screenshots/iPhone 8-label___body_dm.png
  screenshots/iPhone 8-label___body_lm.png
  screenshots/iPhone 8-label___heading_dm.png
  screenshots/iPhone 8-label___heading_lm.png
  screenshots/iPhone 8-label___hero_dm.png
  screenshots/iPhone 8-label___hero_lm.png
  screenshots/iPhone 8-label___multiple-font-styles_dm.png
  screenshots/iPhone 8-label___multiple-font-styles_lm.png
Labels: skip-changelog, documentation

#1589 KOA-5907 BPKText example
  Backpack-SwiftUI/Text/Classes/BPKText.swift
  Backpack-SwiftUI/Text/README.md
  Example/Backpack Screenshot/BackpackSnapshotTestCase.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack/SwiftUI/Components/Text/TextExampleView.swift
  Example/Backpack/Utils/FeatureStories/Groups/TextGroups.swift
  screenshots/iPhone 8-swiftui_text___body_dm.png
  screenshots/iPhone 8-swiftui_text___body_lm.png
  screenshots/iPhone 8-swiftui_text___default_dm.png
  screenshots/iPhone 8-swiftui_text___default_lm.png
  screenshots/iPhone 8-swiftui_text___heading_dm.png
  screenshots/iPhone 8-swiftui_text___heading_lm.png
  screenshots/iPhone 8-swiftui_text___hero_dm.png
  screenshots/iPhone 8-swiftui_text___hero_lm.png
  screenshots/iPhone 8-swiftui_text___multiple-font-styles_dm.png
  screenshots/iPhone 8-swiftui_text___multiple-font-styles_lm.png
Labels: skip-changelog

#1590 Don't generate deprecated colors in SwiftUI
  Backpack-SwiftUI/Color/Classes/Generated/BPKStaticColors.swift
  Backpack-SwiftUI/Tests/Spinner/BPKSpinnerTests.swift
  Backpack-SwiftUI/Tests/Spinner/__Snapshots__/BPKSpinnerTests/test_allSpinnerStyles.light-mode.png
  Backpack-SwiftUI/Tests/Spinner/__Snapshots__/BPKSpinnerTests/test_allSpinnerStyles.rtl.png
  Backpack-SwiftUI/Tests/Text/BPKAttributedTextTests.swift
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKAttributedTextTests/test_multipleItems.dark-mode.png
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKAttributedTextTests/test_multipleItems.light-mode.png
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKAttributedTextTests/test_multipleItems.rtl.png
  gulpfile.js
Labels: minor

#1594 Update BPKNavBar README.md
  Backpack/NavigationBar/README.md
Labels: skip-changelog

#1599 SONIC-1385: fix missing addSubview when titleView & title are set
  Backpack/Rating/Classes/BPKRating.swift
  Backpack/Tests/SnapshotTests/BPKRatingSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.rtl.png
Labels: minor

#1602 KOA-5960 BPKPrice UIKit
  Backpack/Price/Classes/BPKPrice.swift
  Backpack/Price/README.md
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Price/PriceExampleViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/PriceGroupsProvider.swift
  screenshots/iPhone-Price___default_dm.png
  screenshots/iPhone-Price___default_lm.png
  screenshots/iPhone-price___large_dm.png
  screenshots/iPhone-price___large_lm.png
  screenshots/iPhone-price___small_dm.png
  screenshots/iPhone-price___small_lm.png
Labels: patch

#1603 KOA-5960 BPKPrice SwiftUI
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Price/README.md
  Backpack-SwiftUI/Tests/Price/PriceTests.swift
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack/SwiftUI/Components/Price/PriceExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/PriceGroupsProvider.swift
  screenshots/iPhone-swiftui_price___large_dm.png
  screenshots/iPhone-swiftui_price___large_lm.png
  screenshots/iPhone-swiftui_price___small_dm.png
  screenshots/iPhone-swiftui_price___small_lm.png
Labels: patch

#1601 [KOA-5959] Automate Supernova docs publish
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: skip-changelog

#1600 [KOA-5727] Fixing elevated pannels without padding
  Backpack/Panel/Classes/BPKPanel.m
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotElevatedWithoutPadded.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotElevatedWithoutPadded.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotElevatedWithoutPadded.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotWithoutPadded.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotWithoutPadded.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPanelSnapshotTest/testViewSnapshotWithoutPadded.rtl.png
Labels: minor

#1605 BPKFloatingNotification documentation
  Backpack/FloatingNotification/README.md
  Example/Backpack Screenshot/Screenshots.swift
  screenshots/iPhone-floating-notification___default_dm.png
  screenshots/iPhone-floating-notification___default_lm.png
Labels: skip-changelog

#1607 [KOA-5091] Overlay SwiftUI
  Backpack-SwiftUI/Overlay/Classes/BPKOverlay.swift
  Backpack-SwiftUI/Overlay/Classes/OverlayModifier.swift
  Backpack-SwiftUI/Overlay/README.md
  Backpack-SwiftUI/Tests/Overlay/BPKOverlayTests.swift
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearBottomOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearBottomOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearBottomOverlay.rtl.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearLeadingOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearLeadingOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearLeadingOverlay.rtl.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTopOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTopOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTopOverlay.rtl.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTrailingOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTrailingOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_linearTrailingOverlay.rtl.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_solidOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_solidOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_solidOverlay.rtl.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_vignetteOverlay.dark-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_vignetteOverlay.light-mode.png
  Backpack-SwiftUI/Tests/Overlay/__Snapshots__/BPKOverlayTests/test_vignetteOverlay.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Overlay/OverlayExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/OverlayGroupsProvider.swift
  screenshots/iPhone-swiftui_overlay___bottom_dm.png
  screenshots/iPhone-swiftui_overlay___bottom_lm.png
  screenshots/iPhone-swiftui_overlay___leading_dm.png
  screenshots/iPhone-swiftui_overlay___leading_lm.png
  screenshots/iPhone-swiftui_overlay___solid_dm.png
  screenshots/iPhone-swiftui_overlay___solid_lm.png
  screenshots/iPhone-swiftui_overlay___top_dm.png
  screenshots/iPhone-swiftui_overlay___top_lm.png
  screenshots/iPhone-swiftui_overlay___trailing_dm.png
  screenshots/iPhone-swiftui_overlay___trailing_lm.png
  screenshots/iPhone-swiftui_overlay___vignette_dm.png
  screenshots/iPhone-swiftui_overlay___vignette_lm.png
Labels: minor

#1609 updating overlay readme links
  Backpack-SwiftUI/Overlay/README.md
Labels: skip-changelog

#1611 Add supernova as a dependency
  package-lock.json
  package.json
Labels: dependencies

#1613 [KOA-5992] Bump bpk-svgs to update baggage icons
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-lg.imageset/baggage-cabin-add-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-add-sm.imageset/baggage-cabin-add-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-lg.imageset/baggage-cabin-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-lg.imageset/baggage-cabin-not-included-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-not-included-sm.imageset/baggage-cabin-not-included-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-cabin-sm.imageset/baggage-cabin-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-lg.imageset/baggage-checked-add-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-add-sm.imageset/baggage-checked-add-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-lg.imageset/baggage-checked-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-lg.imageset/baggage-checked-not-included-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-not-included-sm.imageset/baggage-checked-not-included-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-checked-sm.imageset/baggage-checked-sm.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-lg.imageset/baggage-generic-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/baggage-generic-sm.imageset/baggage-generic-sm.svg
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.rtl.png
  package-lock.json
  package.json
  screenshots/iPhone-icon___all_dm.png
  screenshots/iPhone-icon___all_lm.png
Labels: minor

#1617 [NO JIRA]: Fix supernova doc deployment step
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: skip-changelog

#1616 KOA-5068 BPKPanel SwiftUI
  Backpack-SwiftUI/Panel/Classes/BPKPanel.swift
  Backpack-SwiftUI/Panel/README.md
  Backpack-SwiftUI/Tests/Panel/BPKPanelTests.swift
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithPadding.dark-mode.png
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithPadding.light-mode.png
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithPadding.rtl.png
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithoutPadding.dark-mode.png
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithoutPadding.light-mode.png
  Backpack-SwiftUI/Tests/Panel/__Snapshots__/BPKPanelTests/test_panelWithoutPadding.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Panel/PanelExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_panel___default_dm.png
  screenshots/iPhone-swiftui_panel___default_lm.png
Labels: minor

#1621 Fix linting issues
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
Labels: skip-changelog

#1620 [SONIC-1384] Build BpkFlightLeg in Backpack
  Backpack/FlightLeg/Classes/BPKFlightLeg.swift
  Backpack/FlightLeg/README.md
  Backpack/Tests/SnapshotTests/BPKFlightLegSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Flight Leg/BPKFlightLegViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  screenshots/iPhone-flight-leg___default_dm.png
  screenshots/iPhone-flight-leg___default_lm.png
Labels: minor, bpk
