Repository Skyscanner/backpack-ios, pull requests merged in 2023-07, with the labels that each got.

#1685 KOA-5976 Make all SwiftUI components not scale
  Backpack-SwiftUI.podspec
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Button/Classes/BPKButton.swift
  Backpack-SwiftUI/Chip/Classes/BPKChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKDropdownChip.swift
  Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Rating/Classes/BPKRating.swift
  Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift
  Backpack-SwiftUI/Utils/Classes/ScaledFont.swift
  Example/Podfile
  Example/Podfile.lock
Labels: skip-changelog, Accessibility

#1690 SwiftUI BPKCard
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
Labels: patch, Accessibility

#1695 Fix page indicator screenshots
  Backpack/PageIndicator/README.md
  Example/Backpack Screenshot/Screenshots.swift
  screenshots/iPhone-page-indicator___default_dm.png
  screenshots/iPhone-page-indicator___default_lm.png
Labels: skip-changelog

#1702 KOA-6214 Introduce icon for ai
  Backpack-Common/Icons/Assets/Media.xcassets/ai-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/ai-lg.imageset/ai-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/ai-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/ai-sm.imageset/ai-sm.svg
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  Backpack-SwiftUI/Tests/Icons/Generated/IconsTestsUtils.swift
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.rtl.png
  Backpack/Icon/Classes/Generated/BPKIconNames.h
  Backpack/Icon/Classes/Generated/BPKIconNames.m
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.h
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.m
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.h
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.m
  Backpack/Tests/SnapshotTests/Utils/BPKIconsTestsUtils.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.rtl.png
  Example/Backpack/SwiftUI/Components/Icons/Generated/BPKIconsExampleUtil.swift
  package-lock.json
  package.json
Labels: minor

#1703 Lint all the things
  Backpack-SwiftUI/Button/Classes/BPKButtonColorSet.swift
  Backpack-SwiftUI/Button/Classes/BPKButtonColors.swift
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
  Backpack-SwiftUI/Card/Classes/BPKCardWrapper.swift
  Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
  Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
  Backpack-SwiftUI/ChipGroup/Classes/BPKSingleSelectChipGroup.swift
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack-SwiftUI/Color/Classes/Generated/BPKInternalColors.swift
  Backpack-SwiftUI/Color/Classes/Generated/BPKStaticColors.swift
  Backpack-SwiftUI/Dialog/Classes/DialogContainerViewModifier.swift
  Backpack-SwiftUI/Dialog/Classes/DialogWithIconContent.swift
  Backpack-SwiftUI/Flare/Classes/BPKFlareView.swift
  Backpack-SwiftUI/Flare/Classes/FlarePath.swift
  Backpack-SwiftUI/Font/Classes/BPKFont.swift
  Backpack-SwiftUI/Font/Classes/Generated/BPKFontStyle.swift
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  Backpack-SwiftUI/PageIndicator/Classes/BPKPageIndicator.swift
  Backpack-SwiftUI/Panel/Classes/BPKPanel.swift
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Radii/Classes/Generated/BPKRadii.swift
  Backpack-SwiftUI/Rating/Classes/BPKRating.swift
  Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton+Size.swift
  Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton.swift
  Backpack-SwiftUI/Slider/Classes/BPKRangeSlider.swift
  Backpack-SwiftUI/Spacing/Classes/BPKSpacing+Extensions.swift
  Backpack-SwiftUI/Spinner/Classes/BPKSpinner.swift
  Backpack-SwiftUI/StarRating/Classes/BPKHotelStarRating.swift
  Backpack-SwiftUI/StarRating/Classes/BPKStarView.swift
  Backpack-SwiftUI/Tests/Card/BPKDividedCardTests.swift
  Backpack-SwiftUI/Tests/ChipGroup/BPKChipGroupTests.swift
  Backpack-SwiftUI/Tests/Font/FontTests.swift
  Backpack-SwiftUI/Tests/Icons/Generated/IconsTestsUtils.swift
  Backpack-SwiftUI/Tests/Price/PriceTests.swift
  Backpack-SwiftUI/Tests/Radii/RadiiTests.swift
  Backpack-SwiftUI/Tests/Rating/BPKRatingTests.swift
  Backpack-SwiftUI/Tests/Shadow/ShadowTests.swift
  Backpack-SwiftUI/Tests/Skeleton/BPKSkeletonTests.swift
  Backpack-SwiftUI/Tests/SnapshotHelpers/SnapshotHelpers.swift
  Backpack-SwiftUI/Tests/Spacing/SpacingTests.swift
  Backpack-SwiftUI/Tests/StarRating/BPKStarRatingTests.swift
  Backpack-SwiftUI/Tests/Text/BPKAttributedTextTests.swift
  Backpack-SwiftUI/Tests/Text/BPKTextDynamicTypeTests.swift
  Backpack-SwiftUI/Tests/Text/BPKTextTests.swift
  Backpack-SwiftUI/Tests/TextField/BPKTextFieldTests.swift
  Backpack-SwiftUI/TextField/Classes/BPKTextField.swift
  Backpack-SwiftUI/Utils/Classes/ScaledFont.swift
  Backpack-SwiftUI/Utils/Classes/View+SizeCategory.swift
  Example/.swiftlint.yml
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
  templates/swiftui/BPKIcons.njk
  templates/swiftui/DynamicColors.njk
  templates/swiftui/Font.njk
  templates/swiftui/IconsTestsUtils.njk
  templates/swiftui/InternalColors.njk
  templates/swiftui/Radii.njk
  templates/swiftui/StaticColors.njk
Labels: skip-changelog

#1704 Apply SwiftLint on BPKCommon
  Backpack-Common/BPKCommonBundle.swift
  Backpack-Common/Icons/Generated/BPKAutoMirrorIconNames.swift
  Example/.swiftlint.yml
  templates/BPKAutoMirrorIconNames.njk
Labels: skip-changelog

#1705 KOA-6210 Align Card Wrapper documentation screenshots
  Backpack/Card/README.md
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack/SwiftUI/Components/Card/CardWrapperExampleView.swift
  Example/Backpack/UIKit/Components/Card/CardWrappersViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/CardGroups.swift
  screenshots/iPhone-card-wrapper___default_dm.png
  screenshots/iPhone-card-wrapper___default_lm.png
  screenshots/iPhone-card-wrapper___not-elevated_dm.png
  screenshots/iPhone-card-wrapper___not-elevated_lm.png
  screenshots/iPhone-card-wrapper___with-corner-style-large_dm.png
  screenshots/iPhone-card-wrapper___with-corner-style-large_lm.png
  screenshots/iPhone-card-wrapper___with-divided-card-not-padded_dm.png
  screenshots/iPhone-card-wrapper___with-divided-card-not-padded_lm.png
  screenshots/iPhone-card-wrapper___with-divided-card_dm.png
  screenshots/iPhone-card-wrapper___with-divided-card_lm.png
  screenshots/iPhone-card-wrapper___with-primary-color_dm.png
  screenshots/iPhone-card-wrapper___with-primary-color_lm.png
  screenshots/iPhone-swiftui_card-wrapper___default_dm.png
  screenshots/iPhone-swiftui_card-wrapper___default_lm.png
  screenshots/iPhone-swiftui_card___default_dm.png
  screenshots/iPhone-swiftui_card___default_lm.png
  screenshots/iPhone-swiftui_divided-card___default_dm.png
  screenshots/iPhone-swiftui_divided-card___default_lm.png
Labels: skip-changelog

#1699 NEUT-1495: Section Header - SwiftUI
  Backpack-SwiftUI/SectionHeader/Classes/BPKSectionHeader.swift
  Backpack-SwiftUI/SectionHeader/Classes/BPKSectionHeaderStyle.swift
  Backpack-SwiftUI/SectionHeader/README.md
  Backpack-SwiftUI/Tests/SectionHeader/BPKSectionHeaderViewTests.swift
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderDefault.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderDefault.light-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderDefault.rtl.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescription.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescription.light-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescription.rtl.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButton.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButton.light-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButton.rtl.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButtonOnDark.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButtonOnDark.light-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButtonOnDark.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/SectionHeader/SectionHeaderExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/SectionHeaderGroups.swift
  screenshots/iPhone-swiftui_section-header___default_dm.png
  screenshots/iPhone-swiftui_section-header___default_lm.png
  screenshots/iPhone-swiftui_section-header___on-dark_dm.png
  screenshots/iPhone-swiftui_section-header___on-dark_lm.png
Labels: swiftui, minor, new-component

#1708 Lumen/lmn 29 bpk select component
  Backpack-SwiftUI/Select/Classes/BPKSelect.swift
  Backpack-SwiftUI/Select/Classes/BPKSelectState.swift
  Backpack-SwiftUI/Select/README.md
  Backpack-SwiftUI/Tests/Select/SelectTests.swift
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_defaultSettings.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_defaultSettings.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_defaultSettings.rtl.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_disabledState.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_disabledState.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_disabledState.rtl.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_emptyOptions.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_emptyOptions.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_emptyOptions.rtl.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_errorState.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_errorState.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_errorState.rtl.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectOutOfBoundsItem.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectOutOfBoundsItem.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectOutOfBoundsItem.rtl.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectSecondItem.dark-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectSecondItem.light-mode.png
  Backpack-SwiftUI/Tests/Select/__Snapshots__/SelectTests/test_selectSecondItem.rtl.png
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Select/SelectExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_select___picker_closed_dm.png
  screenshots/iPhone-swiftui_select___picker_closed_lm.png
  screenshots/iPhone-swiftui_select___picker_open_dm.png
  screenshots/iPhone-swiftui_select___picker_open_lm.png
Labels: swiftui, minor, bpk

#1709 [LMN-17] Bottom sheet component SwiftUI
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheetAction.swift
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheetContentMode.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetHeader.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/BottomSheetShapeModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContentView.swift
  Backpack-SwiftUI/BottomSheet/README.md
  Backpack-SwiftUI/Tests/BottomSheet/BPKBottomSheetTests.swift
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader.dark-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader.rtl.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleAndAction.dark-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleAndAction.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleAndAction.rtl.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleClosable.dark-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleClosable.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleClosable.rtl.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleOnly.dark-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleOnly.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleOnly.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_bottom-sheet___closable_dm.png
  screenshots/iPhone-swiftui_bottom-sheet___closable_lm.png
  screenshots/iPhone-swiftui_bottom-sheet___content-fit_dm.png
  screenshots/iPhone-swiftui_bottom-sheet___content-fit_lm.png
  screenshots/iPhone-swiftui_bottom-sheet___large_dm.png
  screenshots/iPhone-swiftui_bottom-sheet___large_lm.png
  screenshots/iPhone-swiftui_bottom-sheet___medium_dm.png
  screenshots/iPhone-swiftui_bottom-sheet___medium_lm.png
Labels: minor

#1711 NEUT-1548: Add Snippet component in SwiftUI
  Backpack-SwiftUI/Snippet/Classes/BPKSnippet.swift
  Backpack-SwiftUI/Snippet/Classes/BPKSnippetOrientation.swift
  Backpack-SwiftUI/Snippet/README.md
  Backpack-SwiftUI/Tests/Snippet/BPKSnippetViewTests.swift
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetDefault.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetDefault.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetDefault.rtl.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetNoImageWithHeadline.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetNoImageWithHeadline.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetNoImageWithHeadline.rtl.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithAllTextFields.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithAllTextFields.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithAllTextFields.rtl.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithHeadline.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithHeadline.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithHeadline.rtl.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongBodyText.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongBodyText.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongBodyText.rtl.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongDescription.dark-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongDescription.light-mode.png
  Backpack-SwiftUI/Tests/Snippet/__Snapshots__/BPKSnippetViewTests/testSnippetWithLongDescription.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Snippet/SnippetExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/SnippetGroups.swift
  screenshots/iPhone-snippet___landscape_dm.png
  screenshots/iPhone-snippet___landscape_lm.png
  screenshots/iPhone-snippet___portrait_dm.png
  screenshots/iPhone-snippet___portrait_lm.png
  screenshots/iPhone-snippet___square_dm.png
  screenshots/iPhone-snippet___square_lm.png
Labels: swiftui, minor, new-component

#1714 addign missing swiftui screenshots
  screenshots/iPhone-swiftui_badge___default_dm.png
  screenshots/iPhone-swiftui_badge___default_lm.png
  screenshots/iPhone-swiftui_button___destructive_dm.png
  screenshots/iPhone-swiftui_button___destructive_lm.png
  screenshots/iPhone-swiftui_button___featured_dm.png
  screenshots/iPhone-swiftui_button___featured_lm.png
  screenshots/iPhone-swiftui_button___link_dm.png
  screenshots/iPhone-swiftui_button___link_lm.png
  screenshots/iPhone-swiftui_button___primaryOnDark_dm.png
  screenshots/iPhone-swiftui_button___primaryOnDark_lm.png
  screenshots/iPhone-swiftui_button___primaryOnLight_dm.png
  screenshots/iPhone-swiftui_button___primaryOnLight_lm.png
  screenshots/iPhone-swiftui_button___primary_dm.png
  screenshots/iPhone-swiftui_button___primary_lm.png
  screenshots/iPhone-swiftui_button___secondary_dm.png
  screenshots/iPhone-swiftui_button___secondary_lm.png
  screenshots/iPhone-swiftui_spinner___default_dm.png
  screenshots/iPhone-swiftui_spinner___default_lm.png
  screenshots/iPhone-swiftui_switch___default_dm.png
  screenshots/iPhone-swiftui_switch___default_lm.png
Labels: skip-changelog

#1717 Lmn 25/multiselect chip group
  Backpack-SwiftUI/ChipGroup/Classes/BPKMultiSelectChipGroup.swift
  Backpack-SwiftUI/ChipGroup/Classes/BPKStickyChip.swift
  Backpack-SwiftUI/ChipGroup/README.md
  Backpack-SwiftUI/Tests/ChipGroup/BPKChipGroupTests.swift
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railChips_default.dark-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railChips_default.light-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railChips_default.rtl.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railWithStickyChips_default.dark-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railWithStickyChips_default.light-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_railWithStickyChips_default.rtl.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_wrapChips_onDark.dark-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_wrapChips_onDark.light-mode.png
  Backpack-SwiftUI/Tests/ChipGroup/__Snapshots__/BPKChipGroupTests/test_multipleSelect_wrapChips_onDark.rtl.png
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/ChipGroup/MultiSelect/ChipGroupMultipleSelectRailExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/MultiSelect/ChipGroupMultipleSelectWrapExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectRailExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectWrapExampleView.swift
  Example/Backpack/Utils/FeatureStories/Groups/ChipGroupProvider.swift
  screenshots/iPhone-swiftui_chip-group___rail_dm.png
  screenshots/iPhone-swiftui_chip-group___rail_lm.png
  screenshots/iPhone-swiftui_chip-group___wrap_dm.png
  screenshots/iPhone-swiftui_chip-group___wrap_lm.png
Labels: minor
