Repository Skyscanner/backpack-ios, pull requests merged in 2023-08, with the labels that each got.

#1723 fixing invalid whole month selection
  Backpack/Calendar/Classes/BPKCalendar.m
  Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.h
  Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.m
  Backpack/Tests/UnitTests/BPKCalendarMonthDateProviderTests.swift
Labels: patch

#1726 KOA-6242 BPKCalendar, update range color
  Backpack/Calendar/Classes/BPKCalendarCell.m
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithLongRangeSelection.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithLongRangeSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelection.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelectionWithTheme.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelectionWithTheme.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  screenshots/iPhone-calendar___range_dm.png
  screenshots/iPhone-calendar___range_lm.png
Labels: minor

#1724 [LMN-21] SwiftUI Map Markers
  Backpack-SwiftUI/Color/Classes/Generated/BPKInternalColors.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPoiMapMarker+Shape.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPoiMapMarker+State.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPoiMapMarker.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPointerMapMarker.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPriceMapMarker+Shape.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPriceMapMarker+State.swift
  Backpack-SwiftUI/MapMarker/Classes/BPKPriceMapMarker.swift
  Backpack-SwiftUI/MapMarker/README.md
  Backpack-SwiftUI/Tests/MapMarker/BPKMapMarkerTests.swift
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPoiMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPoiMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPoiMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPriceMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPriceMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_defaultPriceMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_disabledPriceMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_disabledPriceMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_disabledPriceMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPoiMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPoiMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPoiMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPriceMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPriceMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_focusedPriceMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_pointerMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_pointerMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_pointerMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPoiMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPoiMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPoiMapMarker.rtl.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPriceMapMarker.dark-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPriceMapMarker.light-mode.png
  Backpack-SwiftUI/Tests/MapMarker/__Snapshots__/BPKMapMarkerTests/test_viewedPriceMapMarker.rtl.png
  Backpack/Color/Classes/Generated/BPKInternalColors.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/MapMarker/MapMarkerExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  package.json
  screenshots/iPhone-swiftui_map-markers___default_dm.png
  screenshots/iPhone-swiftui_map-markers___default_lm.png
Labels: minor

#1732 Nicer screenshots for MultiSelect chip group examples
  Backpack-SwiftUI/ChipGroup/README.md
  Example/Backpack/SwiftUI/Components/ChipGroup/MultiSelect/ChipGroupMultipleSelectRailExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/MultiSelect/ChipGroupMultipleSelectWrapExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectRailExampleView.swift
  Example/Backpack/SwiftUI/Components/ChipGroup/SingleSelect/ChipGroupSingleSelectWrapExampleView.swift
  screenshots/iPhone-swiftui_chip-group-multi___rail_dm.png
  screenshots/iPhone-swiftui_chip-group-multi___rail_lm.png
  screenshots/iPhone-swiftui_chip-group-multi___wrap_dm.png
  screenshots/iPhone-swiftui_chip-group-multi___wrap_lm.png
  screenshots/iPhone-swiftui_chip-group-single___rail_dm.png
  screenshots/iPhone-swiftui_chip-group-single___rail_lm.png
  screenshots/iPhone-swiftui_chip-group-single___wrap_dm.png
  screenshots/iPhone-swiftui_chip-group-single___wrap_lm.png
Labels: skip-changelog

#1733 [KOA-6195] BPKNudger, title and subtitle
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Nudger/README.md
  Backpack-SwiftUI/Tests/Nudger/BPKNudgerTests.swift
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title.rtl.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_subtitle.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_subtitle.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_subtitle.rtl.png
  Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift
  screenshots/iPhone-swiftui_nudger___default_dm.png
  screenshots/iPhone-swiftui_nudger___default_lm.png
Labels: minor

#1735 API to create a BPKIcon with a string
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  templates/swiftui/BPKIcons.njk
Labels: minor

#1739 NEUT-1549: Remove background colour from section header
  Backpack-SwiftUI/SectionHeader/Classes/BPKSectionHeader.swift
  Backpack-SwiftUI/Tests/SectionHeader/BPKSectionHeaderViewTests.swift
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderDefault.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescription.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithDescriptionAndButton.dark-mode.png
  Backpack-SwiftUI/Tests/SectionHeader/__Snapshots__/BPKSectionHeaderViewTests/testSectionHeaderWithLongDescriptionAndButton.dark-mode.png
  Example/Backpack/SwiftUI/Components/SectionHeader/SectionHeaderExampleView.swift
  screenshots/iPhone-swiftui_section-header___default_dm.png
  screenshots/iPhone-swiftui_section-header___default_lm.png
  screenshots/iPhone-swiftui_section-header___on-dark_dm.png
  screenshots/iPhone-swiftui_section-header___on-dark_lm.png
Labels: swiftui, patch, bpk

#1738 Making creation of BPKIcons by name api public
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  templates/swiftui/BPKIcons.njk
Labels: minor

#1741 Removing gesture from dismissable chip
  Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
Labels: patch

#1742 KOA-5977 BPKBadge dynamic type fixes
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Chip/Classes/BPKChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKDropdownChip.swift
  Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
  Backpack-SwiftUI/ChipGroup/Classes/BPKStickyChip.swift
  Backpack-SwiftUI/Font/Classes/BPKFont.swift
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Rating/Classes/BPKRating.swift
  Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift
Labels: minor, Accessibility

#1744 Origami 1916: Add XS BPKprice
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack/Price/Classes/BPKPrice.swift
  Backpack/Price/README.md
  Backpack/Tests/SnapshotTests/BPKPriceSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndExtraSmall.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndExtraSmall.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndExtraSmall.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndExtraSmall.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndExtraSmall.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndExtraSmall.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack/Utils/FeatureStories/Groups/PriceGroupsProvider.swift
  screenshots/iPhone-price___extraSmall_dm.png
  screenshots/iPhone-price___extraSmall_lm.png
  screenshots/iPhone-price___large_dm.png
  screenshots/iPhone-price___large_lm.png
  screenshots/iPhone-price___small_dm.png
  screenshots/iPhone-price___small_lm.png
  screenshots/iPhone-swiftui_price___extraSmall_dm.png
  screenshots/iPhone-swiftui_price___extraSmall_lm.png
  screenshots/iPhone-swiftui_price___large_dm.png
  screenshots/iPhone-swiftui_price___large_lm.png
  screenshots/iPhone-swiftui_price___small_dm.png
  screenshots/iPhone-swiftui_price___small_lm.png
Labels: minor

#1746 [LMN-19] Swiftui Carousel
  Backpack-Common/Carousel/Classes/BPKInternalCarousel.swift
  Backpack-Common/Carousel/Classes/CarouselContentViewController.swift
  Backpack-Common/Carousel/Classes/CarouselPageViewController.swift
  Backpack-Common/Tests/CarouselPageViewControllerTests.swift
  Backpack-SwiftUI/Carousel/Classes/BPKCarousel.swift
  Backpack-SwiftUI/Carousel/README.md
  Backpack-SwiftUI/PageIndicator/Classes/BPKPageIndicator.swift
  Backpack-SwiftUI/Tests/Carousel/BPKCarouselTests.swift
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithOneImage.dark-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithOneImage.light-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithOneImage.rtl.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithSecondSelected.dark-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithSecondSelected.light-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithSecondSelected.rtl.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithThreeImages.dark-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithThreeImages.light-mode.png
  Backpack-SwiftUI/Tests/Carousel/__Snapshots__/BPKCarouselTests/testWithThreeImages.rtl.png
  Backpack/Carousel/Classes/BPKCarousel.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Carousel/CarouselExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_carousel___default_dm.png
  screenshots/iPhone-swiftui_carousel___default_lm.png
Labels: minor

#1750 KOA-6260 update explore icon
  Backpack-Common/Icons/Assets/Media.xcassets/explore-lg.imageset/explore-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/explore-sm.imageset/explore-sm.svg
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.rtl.png
  package-lock.json
  package.json
Labels: minor
