Repository Skyscanner/backpack-ios, pull requests merged in 2023-09, with the labels that each got.

#1753 BPKPrice fix
  Backpack/Price/Classes/BPKPrice.swift
Labels: patch

#1754 [NoJira] Cards are no buttons anymore
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
  Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
Labels: minor

#1756 Revert "[NoJira] Cards are no buttons anymore"
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
  Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
Labels: minor

#1759 SwiftUI BPKIconView
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
Labels: patch

#1758 KOA-6275 Add dynamic font config for Backpack (UIKit)
  Backpack/Font/Classes/BPKFontManager.h
  Backpack/Font/Classes/BPKFontManager.m
  Backpack/Font/Classes/Generated/BPKFont.h
  Backpack/Font/Classes/Generated/BPKFont.m
  Backpack/Label/Classes/BPKLabel.m
  Backpack/Tests/UnitTests/BPKFontTest.m
  Example/Backpack/AppDelegate.swift
  scripts/gulp/fonts.js
  templates/BPKFont.h.njk
  templates/BPKFont.m.njk
Labels: minor

#1766 Update card list examples and screenshots
  Backpack-SwiftUI/Tests/CardList/BPKCardListViewTests.swift
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRail.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRail.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRail.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRailWithSectionHeaderButton.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRailWithSectionHeaderButton.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListRailWithSectionHeaderButton.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStack.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStack.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStack.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessory.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessory.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessory.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButton.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButton.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButton.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButtonAndLongTitleAndDescription.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButtonAndLongTitleAndDescription.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithExpandAccessoryAndSectionHeaderButtonAndLongTitleAndDescription.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithFooterButtonAccessory.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithFooterButtonAccessory.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithFooterButtonAccessory.rtl.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithSectionHeaderButton.dark-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithSectionHeaderButton.light-mode.png
  Backpack-SwiftUI/Tests/CardList/__Snapshots__/BPKCardListViewTests/testCardListStackWithSectionHeaderButton.rtl.png
  Example/Backpack/SwiftUI/Components/CardList/CardListExampleView.swift
  screenshots/iPhone-swiftui_card-list___rail-12-elements-with-section-header-button_dm.png
  screenshots/iPhone-swiftui_card-list___rail-12-elements-with-section-header-button_lm.png
  screenshots/iPhone-swiftui_card-list___rail-3-elements_dm.png
  screenshots/iPhone-swiftui_card-list___rail-3-elements_lm.png
  screenshots/iPhone-swiftui_card-list___stack-3-to-12-elements_dm.png
  screenshots/iPhone-swiftui_card-list___stack-3-to-12-elements_lm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-button_dm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-button_lm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand-with-section-header-button_dm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand-with-section-header-button_lm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand_dm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand_lm.png
Labels: patch, bpk

#1757 KOA-6250 SwiftUI BPKNudger, add optional icon
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Nudger/README.md
  Backpack-SwiftUI/Tests/Nudger/BPKNudgerTests.swift
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_icon.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_icon.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_icon.rtl.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_subtitle_and_icon.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_subtitle_and_icon.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_subtitle_and_icon.rtl.png
  Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift
  screenshots/iPhone-swiftui_nudger___default_dm.png
  screenshots/iPhone-swiftui_nudger___default_lm.png
Labels: minor

#1767 [BugFix] BPKButton accessibility label
  Backpack/Button/Classes/BPKButton.m
  Backpack/Tests/UnitTests/BPKButtonTest.swift
Labels: patch

#1768 Update README.md
  Backpack-SwiftUI/GraphicPromo/README.md
Labels: skip-changelog

#1765 Clean-up unused themes
  Backpack/Theme/Classes/BPKDohaTheme.h
  Backpack/Theme/Classes/BPKDohaTheme.m
  Backpack/Theme/Classes/BPKDohaThemeContainer.h
  Backpack/Theme/Classes/BPKDohaThemeContainer.m
  Backpack/Theme/Classes/BPKHongKongTheme.h
  Backpack/Theme/Classes/BPKHongKongTheme.m
  Backpack/Theme/Classes/BPKHongKongThemeContainer.h
  Backpack/Theme/Classes/BPKHongKongThemeContainer.m
  Backpack/Theme/Classes/BPKLondonTheme.h
  Backpack/Theme/Classes/BPKLondonTheme.m
  Backpack/Theme/Classes/BPKLondonThemeContainer.h
  Backpack/Theme/Classes/BPKLondonThemeContainer.m
  Backpack/Theme/Classes/BPKSilverTheme.h
  Backpack/Theme/Classes/BPKSilverTheme.m
  Backpack/Theme/Classes/BPKSilverThemeContainer.h
  Backpack/Theme/Classes/BPKSilverThemeContainer.m
  Backpack/Theme/Classes/BPKSpringCleanTheme.h
  Backpack/Theme/Classes/BPKSpringCleanTheme.m
  Backpack/Theme/Classes/BPKSpringCleanThemeContainer.h
  Backpack/Theme/Classes/BPKSpringCleanThemeContainer.m
  Backpack/Theme/Classes/Theme.h
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SceneDelegate.swift
  Example/Backpack/Utils/Main.storyboard
  Example/Backpack/Utils/Settings.swift
  Example/Backpack/Utils/Settings/Settings.storyboard
  Example/Backpack/Utils/Settings/SettingsScreenFactory.swift
  Example/Backpack/Utils/Settings/SettingsViewController.swift
  Example/Backpack/Utils/ThemeHelpers.swift
Labels: skip-changelog

#1773 BPKGraphic promo, documentation updates
  Example/Backpack/Images.xcassets/graphic_promo.imageset/Contents.json
  Example/Backpack/Images.xcassets/graphic_promo.imageset/graphic_promo.jpg
  Example/Backpack/SwiftUI/Components/GraphicPromo/GraphicPromoExampleView.swift
  screenshots/iPhone-swiftui_graphic-promo___bottom-aligned-sponsored_dm.png
  screenshots/iPhone-swiftui_graphic-promo___bottom-aligned-sponsored_lm.png
  screenshots/iPhone-swiftui_graphic-promo___bottom-aligned_dm.png
  screenshots/iPhone-swiftui_graphic-promo___bottom-aligned_lm.png
  screenshots/iPhone-swiftui_graphic-promo___top-aligned-sponsored_dm.png
  screenshots/iPhone-swiftui_graphic-promo___top-aligned-sponsored_lm.png
  screenshots/iPhone-swiftui_graphic-promo___top-aligned_dm.png
  screenshots/iPhone-swiftui_graphic-promo___top-aligned_lm.png
Labels: skip-changelog

#1785 NEUT-1765 Add Sponsored Banner SwiftUI Component
  Backpack-SwiftUI/SponsoredBanner/Classes/BPKSponsoredBanner+Extensions.swift
  Backpack-SwiftUI/SponsoredBanner/Classes/BPKSponsoredBanner.swift
  Backpack-SwiftUI/SponsoredBanner/Classes/README.md
  Backpack-SwiftUI/SponsoredBanner/Classes/SponsoredBannerButtonStyle.swift
  Backpack-SwiftUI/Tests/SponsoredBanner/BPKSponsoredBannerViewTests.swift
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithImageWithoutTitleOrSubheadline.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithImageWithoutTitleOrSubheadline.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithImageWithoutTitleOrSubheadline.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithSubheadlineOnly.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithSubheadlineOnly.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnDarkWithSubheadlineOnly.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightVariant.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightVariant.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightVariant.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightWithoutInfoButton.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightWithoutInfoButton.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerOnLightWithoutInfoButton.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerShowingTermsAndConditions.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerShowingTermsAndConditions.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerShowingTermsAndConditions.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithImageTitlesAndCallToAction.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithImageTitlesAndCallToAction.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithImageTitlesAndCallToAction.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithSubheadlineAndBody.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithSubheadlineAndBody.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithSubheadlineAndBody.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitle.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitle.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitle.rtl.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitlesAndCallToAction.dark-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitlesAndCallToAction.light-mode.png
  Backpack-SwiftUI/Tests/SponsoredBanner/__Snapshots__/BPKSponsoredBannerViewTests/testSponsoredBannerWithTitlesAndCallToAction.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/SponsoredBanner/SponsoredBannerExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  package.json
  screenshots/iPhone-swiftui_sponsored-banner___default_dm.png
  screenshots/iPhone-swiftui_sponsored-banner___default_lm.png
Labels: swiftui, minor, new-component

#1778 TEMPURA-757 Add a TextArea Component
  Backpack-SwiftUI/Tests/TextArea/BPKTextAreaTests.swift
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.rtl.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.rtl.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.rtl.png
  Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift
  Backpack-SwiftUI/TextArea/readme.md
  Backpack-SwiftUI/Utils/Classes/Shape.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/TextArea/TextAreaExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_text-area___default_dm.png
  screenshots/iPhone-swiftui_text-area___default_lm.png
Labels: swiftui, minor, bpk, new-component
