Repository Skyscanner/backpack-ios, pull requests merged in 2023-05, with the labels that each got.

#1659 BPKCalendar accessibility improvements
  Backpack/Calendar/Classes/BPKCalendar.m
  Backpack/Calendar/Classes/BPKCalendarPriceLabelCell.m
  Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithCustomColorDates.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithLongRangeSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithMultipleSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithPriceLabels.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithRangeSelectionWithTheme.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithSelectedDateInFuture.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithSingleSelection.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithSingleSelectionAndCustomDisabledDates.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithoutSelection.rtl.png
  Example/Backpack NativeUITests/CalendarUITest.swift
Labels: minor, Accessibility

#1660 [KOA-6077] Node 18 update
  .github/workflows/_build-docs.yml
  .github/workflows/_build.yml
  .nvmrc
  package-lock.json
  package.json
Labels: patch

#1618 KOA-5915 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-changelog

#1665 KOA-6128 Carousel example
  Backpack/Carousel/Classes/BPKCarousel.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack/Images.xcassets/Carousel example/Contents.json
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_1.imageset/Contents.json
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_1.imageset/carousel_placeholder_1.png
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_2.imageset/Contents.json
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_2.imageset/carousel_placeholder_2.png
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_3.imageset/Contents.json
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_3.imageset/carousel_placeholder_3.png
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_4.imageset/Contents.json
  Example/Backpack/Images.xcassets/Carousel example/carousel_placeholder_4.imageset/carousel_placeholder_4.png
  Example/Backpack/UIKit/Components/Carousel/CarouselViewController.swift
  screenshots/iPhone-carousel___default_dm.png
  screenshots/iPhone-carousel___default_lm.png
Labels: patch

#1663 Update CONTRIBUTING.md experimentation guidelines
  CONTRIBUTING.md
Labels: skip-changelog
