Repository Skyscanner/backpack-ios, pull requests merged in 2023-02, with the labels that each got.

#1551 KOA-5797 BPKChip update
  Backpack-SwiftUI/Color/Classes/Generated/BPKInternalColors.swift
  Backpack/Chip/Classes/BPKChip.swift
  Backpack/Chip/Classes/BPKChipColors.swift
  Backpack/Chip/Classes/BPKChipStyle.swift
  Backpack/Chip/Classes/BPKChipType.swift
  Backpack/Chip/README.md
  Backpack/Color/Classes/Generated/BPKInternalColors.swift
  Backpack/Tests/SnapshotTests/BPKChipSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithSelectType.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithSelectType.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithSelectType.rtl.png
  Example/Backpack NativeUITests/ChipUITest.swift
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/Backpack-Info.plist
  Example/Backpack/UIKit/Components/Chip/ChipPreviewCollectionViewCell.swift
  Example/Backpack/UIKit/Components/Chip/ChipSelectorViewController.swift
  Example/Backpack/UIKit/Components/Chip/Chips.storyboard
  Example/Backpack/UIKit/Components/Chip/ChipsViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/ChipGroups.swift
  package-lock.json
  package.json
  screenshots/iPhone 8-chip___default_dm.png
  screenshots/iPhone 8-chip___default_lm.png
  screenshots/iPhone 8-chip___on-dark_dm.png
  screenshots/iPhone 8-chip___on-dark_lm.png
  screenshots/iPhone 8-chip___on-image_dm.png
  screenshots/iPhone 8-chip___on-image_lm.png
Labels: major

#1556 KOA-5797 BPKChip fixes
  Backpack/Chip/Classes/BPKChip.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipDisabled.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipSelectedWithIcon.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipUnselected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDismissType.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithDropdownType.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKChipSnapshotTest/testChipWithIcon.rtl.png
  Backpack/Theme/Classes/BPKTheme.m
Labels: patch

#1560 [no jira]: Remove spellcheck library
  .spelling
  package-lock.json
  package.json
Labels: skip-changelog

#1555 [KOA-5649] Remove references to backpack.github.io
  Backpack/Icon/README.md
  Backpack/Tests/SnapshotTests/BPKTappableLinkLabelSnapshotTest.swift
  CONTRIBUTING.md
  Example/Backpack/UIKit/Components/Link/TappableLinkLabelsViewController.swift
  README.md
Labels: skip-changelog

#1557 BPKPageIndicator contribution
  Backpack-SwiftUI/PageIndicator/Classes/BPKPageIndicator.swift
  Backpack/PageIndicator/Classes/BPKPageIndicator.swift
  Backpack/Tests/SnapshotTests/BPKPageIndicatorSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotDarkBackground.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotDarkBackground.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotDarkBackground.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotWithDefault.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotWithDefault.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPageIndicatorSnapshotTest/testViewSnapshotWithDefault.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/PageIndicator/PageIndicatorExampleView.swift
  Example/Backpack/UIKit/Components/PageIndicator/PageIndicatorViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone 8-page indicator___default_dm.png
  screenshots/iPhone 8-page indicator___default_lm.png
Labels: minor

#1558 Add BPKCardWrapper component to SwiftUI
  Backpack-SwiftUI/Card/Classes/BPKCard.swift
  Backpack-SwiftUI/Card/Classes/BPKCardWrapper.swift
  Backpack-SwiftUI/Card/Classes/CardWrappable.swift
  Backpack-SwiftUI/Card/README.md
  Backpack-SwiftUI/Tests/Card/CardWrapperTests.swift
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCard.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCard.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCard.rtl.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCorePrimaryColorBackground.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCorePrimaryColorBackground.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithCorePrimaryColorBackground.rtl.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithDividedCard.dark-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithDividedCard.light-mode.png
  Backpack-SwiftUI/Tests/Card/__Snapshots__/CardWrapperTests/testWithDividedCard.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Card/CardWrapperExampleView.swift
  Example/Backpack/Utils/FeatureStories/Groups/CardGroups.swift
  screenshots/iPhone 8-swiftui_card-wrapper___default_dm.png
  screenshots/iPhone 8-swiftui_card-wrapper___default_lm.png
Labels: swiftui, minor

#1570 [KOA-5736] Deprecating dynamicColor
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack/Color/Classes/Generated/BPKColor.h
  templates/BPKColor.h.njk
  templates/swiftui/DynamicColors.njk
Labels: minor

#1565 [KOA-5896]: Add new Origin icon
  Backpack-Common/Icons/Assets/Media.xcassets/origin-lg.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/origin-lg.imageset/origin-lg.svg
  Backpack-Common/Icons/Assets/Media.xcassets/origin-sm.imageset/Contents.json
  Backpack-Common/Icons/Assets/Media.xcassets/origin-sm.imageset/origin-sm.svg
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  Backpack-SwiftUI/Tests/Icons/Generated/IconsTestsUtils.swift
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllLargeIcons.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testAllSmallIcons.rtl.png
  Backpack/Icon/Classes/Generated/BPKIconNames.h
  Backpack/Icon/Classes/Generated/BPKIconNames.m
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.h
  Backpack/Icon/Classes/Generated/BPKLargeIconNames.m
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.h
  Backpack/Icon/Classes/Generated/BPKSmallIconNames.m
  Backpack/Tests/SnapshotTests/Utils/BPKIconsTestsUtils.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllLargeIcons.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKIconSnapshotTest/testAllSmallIcons.rtl.png
  Example/Backpack/SwiftUI/Components/Icons/Generated/BPKIconsExampleUtil.swift
  package-lock.json
  package.json
  screenshots/iPhone 8-icon___all_dm.png
  screenshots/iPhone 8-icon___all_lm.png
Labels: minor

#1571 Update icon and launch screen
  Example/Backpack/Base.lproj/LaunchScreen.xib
  Example/Backpack/Images.xcassets/AppIcon.appiconset/Contents.json
  Example/Backpack/Images.xcassets/AppIcon.appiconset/appIcon.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon1024.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon20.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon20@2x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon20@3x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon29.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon29@2x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon29@3x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon40@2x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon40@3x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon60@2x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon60@3x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon76.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon76@2x.png
  Example/Backpack/Images.xcassets/AppIcon.appiconset/icon83.5@2x.png
  Example/Backpack/Images.xcassets/LaunchScreenBackground.colorset/Contents.json
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Contents.json
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient.png
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient@2x.png
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient@3x.png
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient_dm.png
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient_dm@2x.png
  Example/Backpack/Images.xcassets/LaunchScreenGradient.imageset/Gradient_dm@3x.png
  Example/Backpack/Images.xcassets/LaunchScreenIcon.imageset/Contents.json
  Example/Backpack/Images.xcassets/LaunchScreenIcon.imageset/launch_logo_dm.svg
  Example/Backpack/Images.xcassets/LaunchScreenIcon.imageset/launch_logo_lm.svg
  Example/Backpack/Images.xcassets/LaunchScreenIcon.imageset/logo@x3.png
Labels: skip-changelog

#1573 BPKPrice
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Text/Classes/BPKText.swift
  Backpack/Price/Classes/BPKPrice.swift
  Backpack/Tests/SnapshotTests/BPKPriceSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndLarge.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndLarge.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndLarge.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndSmall.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndSmall.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithLeadingAndSmall.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoLeadingText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoLeadingText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoLeadingText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoPreviousPrice.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoPreviousPrice.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoPreviousPrice.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoTrailingText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoTrailingText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithNoTrailingText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithPriceOnly.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithPriceOnly.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithPriceOnly.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndLarge.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKPriceSnapshotTest/testViewSnapshotWithTrailingAndSmall.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Price/PriceExampleView.swift
  Example/Backpack/UIKit/Components/Price/PriceExampleViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  screenshots/iPhone 8-Price___default_dm.png
  screenshots/iPhone 8-Price___default_lm.png
Labels: minor

#1572 BPKCarousel contribution
  Backpack/Carousel/Classes/BPKCarousel.swift
  Backpack/Carousel/Classes/CarouselContentViewController.swift
  Backpack/Carousel/Classes/CarouselPageViewController.swift
  Backpack/Tests/SnapshotTests/BPKCarouselSnapshotTest.swift
  Backpack/Tests/SnapshotTests/Images.xcassets/dialog_flare.imageset/Contents.json
  Backpack/Tests/SnapshotTests/Images.xcassets/dialog_flare.imageset/dialog_flare.jpg
  Backpack/Tests/SnapshotTests/Images.xcassets/dialog_image.imageset/Contents.json
  Backpack/Tests/SnapshotTests/Images.xcassets/dialog_image.imageset/dialog_image.jpg
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithOneImage.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithOneImage.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithOneImage.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithSecondSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThirdSelected.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithThreeImages.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCarouselSnapshotTest/testViewSnapshotWithTwoImages.rtl.png
  Backpack/Tests/UnitTests/CarouselPageViewControllerTests.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Carousel/CarouselViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
Labels: minor

#1564 Sonic-1376 BPKShareCardButton & BPKSaveCardButton
  Backpack/CardButton/Classes/CardButtonBackgroundView.swift
  Backpack/CardButton/Classes/CardButtonSize.swift
  Backpack/CardButton/Classes/CardButtonStyle.swift
  Backpack/CardButton/Classes/SaveCardButton+Style.swift
  Backpack/CardButton/Classes/SaveCardButton.swift
  Backpack/CardButton/Classes/ShareCardButton.swift
  Backpack/CardButton/README.md
  Backpack/Tests/SnapshotTests/BPKBadgeSnapshotTest.swift
  Backpack/Tests/SnapshotTests/BPKMapAnnotationSnapshotTest.swift
  Backpack/Tests/SnapshotTests/BPKSaveCardButtonSnapshotTest.swift
  Backpack/Tests/SnapshotTests/BPKShareCardButtonSnapshotTest.swift
  Backpack/Tests/SnapshotTests/BPKSwitchSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testCheckedSaveCardButtonSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testCheckedSaveCardButtonSnapshot.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testCheckedSaveCardButtonSnapshot.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testUncheckedSaveCardButtonSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testUncheckedSaveCardButtonSnapshot.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKSaveCardButtonSnapshotTest/testUncheckedSaveCardButtonSnapshot.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKShareCardButtonSnapshotTest/testShareCardButtonSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKShareCardButtonSnapshotTest/testShareCardButtonSnapshot.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKShareCardButtonSnapshotTest/testShareCardButtonSnapshot.rtl.png
  Backpack/Tests/UnitTests/BPKSaveCardButtonTest.swift
  Backpack/Tests/UnitTests/BPKShareCardButtonTest.swift
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Card/Card Button/CardButtonsViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone 8-cardButton___all_dm.png
  screenshots/iPhone 8-cardButton___all_lm.png
Labels: minor

#1566 Screenshot docs enhancement
  CONTRIBUTING.md
Labels: skip-changelog

#1577 BPKBadge accessibility outline
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack/Badge/Classes/Badge.swift
Labels: Accessibility, patch

#1576 Add BPKCardWrapper component to UIKit
  Backpack/Card/Classes/BPKCardElevation.swift
  Backpack/Card/Classes/BPKCardWrapper.swift
  Backpack/Card/README.md
  Backpack/Tests/SnapshotTests/BPKCardWrapperSnapshotTests.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCard.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCard.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCard.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndCorneStyleLarge.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndCorneStyleLarge.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndCorneStyleLarge.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndPrimaryColor.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndPrimaryColor.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardAndPrimaryColor.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardNotElevated.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardNotElevated.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithCardNotElevated.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCard.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCard.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCard.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCardAndNotPadded.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCardAndNotPadded.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCardWrapperSnapshotTests/testViewSnapshotWithDividedCardAndNotPadded.rtl.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/UIKit/Components/Card/CardWrappersViewController.swift
  Example/Backpack/Utils/FeatureStories/Groups/CardGroups.swift
  screenshots/iPhone 8-card-wrapper___default_dm.png
  screenshots/iPhone 8-card-wrapper___default_lm.png
  screenshots/iPhone 8-card-wrapper___not-elevated_dm.png
  screenshots/iPhone 8-card-wrapper___not-elevated_lm.png
  screenshots/iPhone 8-card-wrapper___with-corner-style-large_dm.png
  screenshots/iPhone 8-card-wrapper___with-corner-style-large_lm.png
  screenshots/iPhone 8-card-wrapper___with-divided-card-not-padded_dm.png
  screenshots/iPhone 8-card-wrapper___with-divided-card-not-padded_lm.png
  screenshots/iPhone 8-card-wrapper___with-divided-card_dm.png
  screenshots/iPhone 8-card-wrapper___with-divided-card_lm.png
  screenshots/iPhone 8-card-wrapper___with-primary-color_dm.png
  screenshots/iPhone 8-card-wrapper___with-primary-color_lm.png
Labels: minor

#1580 BPKFloatingNotification
  Backpack/FloatingNotification/Classes/BPKFloatingNotification.swift
  Backpack/FloatingNotification/Classes/FloatingNotificationAnimator.swift
  Backpack/FloatingNotification/Classes/FloatingNotificationView.swift
  Backpack/FloatingNotification/Classes/FloatingNotificationViewModel.swift
  Backpack/Tests/SnapshotTests/BPKFloatingNotificationSnapshotTests.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndLongTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithIconAndTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustLongTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustText.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustText.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustText.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustTextForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustTextForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithJustTextForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.rtl.png
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native.xcscheme
  Example/Backpack/UIKit/Components/FloatingNotification/FloatingNotificationViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
Labels: minor

#1584 BPKCarousel: Disabling scrolling when setting one image
  Backpack/Carousel/Classes/CarouselPageViewController.swift
Labels: minor
