Repository Skyscanner/backpack-ios, pull requests merged in 2023-04, with the labels that each got.

#1625 [KOA-6006] Readmes for carousel and page indicator
  Backpack/Carousel/README.md
  Backpack/PageIndicator/README.md
  screenshots/iPhone-carousel___default_dm.png
  screenshots/iPhone-carousel___default_lm.png
Labels: skip-changelog

#1622 [KOA-5994] Making the title not required in bpkrating
  Backpack/Rating/Classes/BPKRating.swift
Labels: major

#1627 [KOA-5082] Nudger swiftui
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Nudger/README.md
  Backpack-SwiftUI/Tests/Nudger/BPKNudgerTests.swift
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_maxValue.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_maxValue.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_maxValue.rtl.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_minValue.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_minValue.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_minValue.rtl.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_validValue.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_validValue.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_validValue.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-nudger___default_dm.png
  screenshots/iPhone-nudger___default_lm.png
  screenshots/iPhone-swiftui_nudger___default_dm.png
  screenshots/iPhone-swiftui_nudger___default_lm.png
Labels: minor

#1628 Using UIImageView instead of BPKIconView for airline logo
  Backpack/FlightLeg/Classes/BPKFlightLeg.swift
  Backpack/Tests/SnapshotTests/BPKFlightLegSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegSnapshotDefaultDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteArabicDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithCompleteLongStopsInfoDescription.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFlightLegSnapshotTest/testBPKFlightLegWithExtraStops.rtl.png
  Example/Backpack/UIKit/Components/Flight Leg/BPKFlightLegViewController.swift
Labels: minor

#1633 [NoJira] Enabling updates of price related values
  Backpack/Price/Classes/BPKPrice.swift
  Backpack/Rating/Classes/BPKRating.swift
  Backpack/Tests/SnapshotTests/BPKPriceSnapshotTest.swift
  Backpack/Tests/SnapshotTests/BPKRatingSnapshotTest.swift
  Example/Backpack/UIKit/Components/Price/PriceExampleViewController.swift
  Example/Backpack/UIKit/Components/Rating/RatingsViewController.swift
Labels: major

#1634 [KOA-5090] BPKFlareView Swiftui
  Backpack-SwiftUI/Flare/Classes/BPKFlareView.swift
  Backpack-SwiftUI/Flare/Classes/FlarePath.swift
  Backpack-SwiftUI/Flare/README.md
  Backpack-SwiftUI/Tests/Flare/BPKFlareTests.swift
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testLargeFlareView.dark-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testLargeFlareView.light-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testLargeFlareView.rtl.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testMediumFlareView.dark-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testMediumFlareView.light-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testMediumFlareView.rtl.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testRectFlareView.dark-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testRectFlareView.light-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testRectFlareView.rtl.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testSmallFlareView.dark-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testSmallFlareView.light-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testSmallFlareView.rtl.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testTopFlareView.dark-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testTopFlareView.light-mode.png
  Backpack-SwiftUI/Tests/Flare/__Snapshots__/BPKFlareTests/testTopFlareView.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Flare/FlareExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-flare-view___background-image_dm.png
  screenshots/iPhone-flare-view___background-image_lm.png
  screenshots/iPhone-flare-view___default_dm.png
  screenshots/iPhone-flare-view___default_lm.png
  screenshots/iPhone-flare-view___flare-at-top_dm.png
  screenshots/iPhone-flare-view___flare-at-top_lm.png
  screenshots/iPhone-flare-view___rounded_dm.png
  screenshots/iPhone-flare-view___rounded_lm.png
  screenshots/iPhone-swiftui_flare-view___all_dm.png
  screenshots/iPhone-swiftui_flare-view___all_lm.png
Labels: swiftui, minor, new-component

#1638 [KOA-5958] Swiftifying token usage and adding documentation to extensions
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Button/Classes/BPKButton.swift
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Panel/README.md
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Rating/Classes/BPKRating.swift
  Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton+Size.swift
  Backpack-SwiftUI/Spacing/Classes/BPKSpacing+Extensions.swift
  Backpack-SwiftUI/Spacing/Classes/Generated/BPKSpacing.swift
  Backpack-SwiftUI/Tests/Rating/BPKRatingTests.swift
  Example/Backpack/SwiftUI/Components/Panel/PanelExampleView.swift
  Example/Backpack/SwiftUI/Components/Price/PriceExampleView.swift
  Example/Backpack/SwiftUI/Components/Rating/RatingExampleViewWithImage.swift
  Example/Backpack/SwiftUI/Components/Rating/RatingExampleViewWithTitle.swift
  Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
  templates/swiftui/Spacing.njk
Labels: minor

#1639 BPKRating right-to-left fix
  Backpack-Common/BPKCommonRatingScale.swift
  Backpack-SwiftUI/Rating/Classes/BPKRating.swift
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithString.dark-mode.png
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithString.light-mode.png
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithString.rtl.png
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithTitleView.dark-mode.png
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithTitleView.light-mode.png
  Backpack-SwiftUI/Tests/Rating/__Snapshots__/BPKRatingTests/test_ratingsWithTitleView.rtl.png
  Backpack/Rating/Classes/BPKRating.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingSnapshot.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingSnapshot.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingSnapshot.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetASecondTitleView.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleConstraintUpdateAfterSetTitle.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKRatingSnapshotTest/testBPKRatingTitleViewConstraintUpdateAfterSetTitleView.rtl.png
Labels: patch

#1629 BPKHorizontal navigation Accessibility fix
  Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
  Example/Backpack NativeUITests/HorizontalNavigationUITest.swift
Labels: patch, Accessibility

#1626 [KOA-5078] Adding text field swiftui component
  Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
  Backpack-SwiftUI/Tests/TextField/BPKTextFieldTests.swift
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_clearableField.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_clearableField.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_clearableField.rtl.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_defaultSettings.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_defaultSettings.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_defaultSettings.rtl.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_disabledField.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_disabledField.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_disabledField.rtl.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_emptyField.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_emptyField.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_emptyField.rtl.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_errorField.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_errorField.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_errorField.rtl.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_validField.dark-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_validField.light-mode.png
  Backpack-SwiftUI/Tests/TextField/__Snapshots__/BPKTextFieldTests/test_validField.rtl.png
  Backpack-SwiftUI/TextField/Classes/BPKTextField.swift
  Backpack-SwiftUI/TextField/Classes/BPKTextFieldState.swift
  Backpack-SwiftUI/TextField/README.md
  Backpack-SwiftUI/Utils/Classes/Outline.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/TextField/TextFieldExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_text-field___default_dm.png
  screenshots/iPhone-swiftui_text-field___default_lm.png
  screenshots/iPhone-text-field___default_dm.png
  screenshots/iPhone-text-field___default_lm.png
Labels: swiftui, minor, new-component

#1631 [KOA-5077] BPKDialog SwiftUI
  Backpack-SwiftUI.podspec
  Backpack-SwiftUI/Button/Classes/BPKButton.swift
  Backpack-SwiftUI/Button/Classes/CurrentStateButtonStyle.swift
  Backpack-SwiftUI/Dialog/Classes/BPKDialog.swift
  Backpack-SwiftUI/Dialog/Classes/BPKDialogButton.swift
  Backpack-SwiftUI/Dialog/Classes/DialogActionsView.swift
  Backpack-SwiftUI/Dialog/Classes/DialogContainerViewModifier.swift
  Backpack-SwiftUI/Dialog/Classes/DialogImageView.swift
  Backpack-SwiftUI/Dialog/Classes/DialogTextContent.swift
  Backpack-SwiftUI/Dialog/Classes/DialogWithHeaderContent.swift
  Backpack-SwiftUI/Dialog/Classes/DialogWithIconContent.swift
  Backpack-SwiftUI/Dialog/README.md
  Backpack-SwiftUI/Tests/Dialog/BPKDialogTests.swift
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_customHeaderDialog.dark-mode.png
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_customHeaderDialog.light-mode.png
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_customHeaderDialog.rtl.png
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_iconDialog.dark-mode.png
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_iconDialog.light-mode.png
  Backpack-SwiftUI/Tests/Dialog/__Snapshots__/BPKDialogTests/test_iconDialog.rtl.png
  Backpack-SwiftUI/Tests/Images.xcassets/Contents.json
  Backpack-SwiftUI/Tests/Images.xcassets/dialog_flare.imageset/Contents.json
  Backpack-SwiftUI/Tests/Images.xcassets/dialog_flare.imageset/dialog_flare.jpg
  Backpack-SwiftUI/Tests/Images.xcassets/dialog_image.imageset/Contents.json
  Backpack-SwiftUI/Tests/Images.xcassets/dialog_image.imageset/dialog_image.jpg
  Backpack-SwiftUI/Tests/SnapshotHelpers/bundleProvider.swift
  Backpack-SwiftUI/Utils/Classes/ConditionalModifier.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Dialog/DialogExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Podfile.lock
  screenshots/iPhone-dialog___destructive_dm.png
  screenshots/iPhone-dialog___destructive_lm.png
  screenshots/iPhone-dialog___flare_dm.png
  screenshots/iPhone-dialog___flare_lm.png
  screenshots/iPhone-dialog___image_dm.png
  screenshots/iPhone-dialog___image_lm.png
  screenshots/iPhone-dialog___success_dm.png
  screenshots/iPhone-dialog___success_lm.png
  screenshots/iPhone-dialog___warning_dm.png
  screenshots/iPhone-dialog___warning_lm.png
  screenshots/iPhone-swiftui_dialog___destructive_dm.png
  screenshots/iPhone-swiftui_dialog___destructive_lm.png
  screenshots/iPhone-swiftui_dialog___flare_dm.png
  screenshots/iPhone-swiftui_dialog___flare_lm.png
  screenshots/iPhone-swiftui_dialog___image_dm.png
  screenshots/iPhone-swiftui_dialog___image_lm.png
  screenshots/iPhone-swiftui_dialog___success_dm.png
  screenshots/iPhone-swiftui_dialog___success_lm.png
  screenshots/iPhone-swiftui_dialog___warning_dm.png
  screenshots/iPhone-swiftui_dialog___warning_lm.png
Labels: swiftui, minor, new-component

#1632 [KOA-5084] BPKStarRating SwiftUI
  Backpack-SwiftUI/StarRating/Classes/BPKHotelStarRating.swift
  Backpack-SwiftUI/StarRating/Classes/BPKStarRating.swift
  Backpack-SwiftUI/StarRating/Classes/BPKStarRatingSize.swift
  Backpack-SwiftUI/StarRating/Classes/BPKStarView.swift
  Backpack-SwiftUI/StarRating/README.md
  Backpack-SwiftUI/Tests/StarRating/BPKStarRatingTests.swift
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_customNumberOfStars.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_customNumberOfStars.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_customNumberOfStars.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_downRounding.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_downRounding.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_downRounding.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_fullStars.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_fullStars.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_fullStars.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_halfStar.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_halfStar.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_halfStar.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_hotelStars.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_hotelStars.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_hotelStars.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_largeSize.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_largeSize.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_largeSize.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_nearestRounding.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_nearestRounding.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_nearestRounding.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_upRounding.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_upRounding.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_upRounding.rtl.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_zeroStars.dark-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_zeroStars.light-mode.png
  Backpack-SwiftUI/Tests/StarRating/__Snapshots__/BPKStarRatingTests/test_zeroStars.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/StarRating/StarRatingExampleView.swift
  Example/Backpack/SwiftUI/Components/StarRating/StarRatingPlayground.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/StarRatingGroupsProvider.swift
  screenshots/iPhone-swiftui_star-rating___all_dm.png
  screenshots/iPhone-swiftui_star-rating___all_lm.png
Labels: swiftui, minor, new-component

#1641 Allow the carrierLogo to be set at a later stage
  Backpack/FlightLeg/Classes/BPKFlightLeg.swift
Labels: minor

#1640 BPKSlider setups
  Backpack-SwiftUI/ExampleComponent/README.md
  Backpack-SwiftUI/Slider/Classes/BPKRangeSlider.swift
  Backpack-SwiftUI/Slider/Classes/BPKSlider.swift
  Backpack-SwiftUI/Slider/Classes/BPKSliderHelpers.swift
  Backpack-SwiftUI/Slider/Classes/SliderThumbView.swift
  Backpack-SwiftUI/Slider/README.md
  Backpack-SwiftUI/Tests/Slider/SliderTests.swift
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.dark-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.light-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRangeSlider.rtl.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRegularSlider.dark-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRegularSlider.light-mode.png
  Backpack-SwiftUI/Tests/Slider/__Snapshots__/SliderTests/testRegularSlider.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Slider/SliderExampleView.swift
  Example/Backpack/SwiftUI/Components/Slider/SliderPlayground.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/SliderGroups.swift
  screenshots/iPhone-swiftui_slider___all_dm.png
  screenshots/iPhone-swiftui_slider___all_lm.png
Labels: swiftui, minor, new-component

#1646 [KOA-5970] Add experimentation guidelines
  CONTRIBUTING.md
Labels: skip-changelog

#1642 Chips on SwiftUI
  Backpack-SwiftUI/Chip/Classes/BPKChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKChipStyle.swift
  Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
  Backpack-SwiftUI/Chip/Classes/BPKDropdownChip.swift
  Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
  Backpack-SwiftUI/Chip/README.md
  Backpack-SwiftUI/Tests/Chip/BPKChipTests.swift
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDismissable.dark-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDismissable.light-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDismissable.rtl.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDropdown.dark-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDropdown.light-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipDropdown.rtl.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipSelected.dark-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipSelected.light-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipSelected.rtl.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipWithIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipWithIcon.light-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_chipWithIcon.rtl.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_textChip.dark-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_textChip.light-mode.png
  Backpack-SwiftUI/Tests/Chip/__Snapshots__/BPKChipTests/test_textChip.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/Images.xcassets/canadian_rockies_canada.imageset/Contents.json
  Example/Backpack/Images.xcassets/canadian_rockies_canada.imageset/canadian_rockies_canada.jpg
  Example/Backpack/SwiftUI/Components/Chip/ChipExampleView.swift
  Example/Backpack/UIKit/Components/Chip/ChipsViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  Example/Backpack/Utils/FeatureStories/Groups/ChipGroups.swift
  screenshots/iPhone-chip___default_dm.png
  screenshots/iPhone-chip___default_lm.png
  screenshots/iPhone-chip___on-dark_dm.png
  screenshots/iPhone-chip___on-dark_lm.png
  screenshots/iPhone-chip___on-image_dm.png
  screenshots/iPhone-chip___on-image_lm.png
  screenshots/iPhone-swiftui_chip___default_dm.png
  screenshots/iPhone-swiftui_chip___default_lm.png
  screenshots/iPhone-swiftui_chip___on-dark_dm.png
  screenshots/iPhone-swiftui_chip___on-dark_lm.png
  screenshots/iPhone-swiftui_chip___on-image_dm.png
  screenshots/iPhone-swiftui_chip___on-image_lm.png
Labels: swiftui, minor, new-component

#1649 KOA-6066 Introduce new color token
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack/Color/Classes/Generated/BPKColor.h
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/Color/Classes/Generated/UIColor+Backpack.h
  Backpack/Color/Classes/Generated/UIColor+Backpack.m
  Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
  package-lock.json
  package.json
Labels: minor

#1654 Add support for setting distribution of BPKDividedCard
  Backpack/Card/Classes/BPKDividedCard.h
  Backpack/Card/Classes/BPKDividedCard.m
Labels: minor
