Repository Skyscanner/backpack-ios, pull requests merged in 2024-12, with the labels that each got.

#2121 Fix onTapGesture for BPKDividedCard
  Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
Labels: minor, Accessibility

#2124 [DON-1037] Fix BPKCalendar scroll view
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarContainer.swift
Labels: swiftui, minor

#2100 [AI-807][ChAI]: Card carousel fixes
  Backpack-SwiftUI/CardCarousel/Classes/BPKCardCarousel.swift
  Backpack-SwiftUI/CarouselCard/Classes/BPKCarouselCard.swift
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_full.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_full.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_full.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_half.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_half.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_half.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_third.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_third.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_third.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_two_thirds.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_two_thirds.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_landscape_two_thirds.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_full.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_full.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_full.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_third.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_third.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_third.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_two_thirds.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_two_thirds.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/ipad_potrait_two_thirds.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/testCardCarousel.dark-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/testCardCarousel.light-mode.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/testCardCarousel.rtl.png
  Backpack-SwiftUI/Tests/CardCarousel/__Snapshots__/BPKCardCarouselTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.dark-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.light-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.rtl.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/test_accessibility.a11y.png
  screenshots/iPhone-card-carousel__default_dm.png
  screenshots/iPhone-card-carousel__default_lm.png
Labels: minor
