Repository Skyscanner/backpack-ios, pull requests merged in 2024-04, with the labels that each got.

#1929 OGM-2374: New component - Navigation Tab Group
  Backpack-SwiftUI/NavigationTab/Classes/BPKNavigationTab+Style.swift
  Backpack-SwiftUI/NavigationTab/Classes/BPKNavigationTab.swift
  Backpack-SwiftUI/NavigationTab/Classes/BPKNavigationTabGroup.swift
  Backpack-SwiftUI/NavigationTab/Classes/NavigationTabStyle.swift
  Backpack-SwiftUI/Tests/NavigationTab/BPKNavigationTabGroupTests.swift
  Backpack-SwiftUI/Tests/NavigationTab/BPKNavigationTabTests.swift
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_dark.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_dark.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_dark.rtl.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_default.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_default.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabGroupTests/test_default.rtl.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabSelected.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabSelected.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabSelected.rtl.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabWithIcon.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabWithIcon.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_navigationTabWithIcon.rtl.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_textNavigationTab.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_textNavigationTab.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTab/__Snapshots__/BPKNavigationTabTests/test_textNavigationTab.rtl.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_dark.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_dark.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_dark.rtl.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_default.dark-mode.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_default.light-mode.png
  Backpack-SwiftUI/Tests/NavigationTabGroup/__Snapshots__/BPKNavigationTabGroupTests/test_default.rtl.png
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/NavigationTabGroup/NavigationTabGroupExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
Labels: minor

#1930 DON-384: Update SearchField sizes and accessibility for the Place Selector GC
  Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
  Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/BPKSearchInputSummaryTests.swift
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_clearableField_withPrefixIcon.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_defaultSettings_withPrefixIcon.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_disabledField_withPrefixIcon.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_emptyField_withPrefixIcon.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_errorField_withPrefixIcon.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withCustomPrefixText.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withCustomPrefixText.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withCustomPrefixText.rtl.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withPrefixIcon.dark-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withPrefixIcon.light-mode.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_validField_withPrefixIcon.rtl.png
Labels: minor, Accessibility

#1931 DON-384: Adjust the TextField of the Place Selector GC
  Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.rtl.png
Labels: minor

#1933 Migrate to asdf for managing versions
  .github/workflows/_build-docs.yml
  .github/workflows/_build.yml
  .github/workflows/_test.yml
  .github/workflows/release.yml
  .nvmrc
  .ruby-version
  .tool-versions
  CONTRIBUTING.md
  fullsetup
Labels: skip-changelog

#1937 Add BPKHorizontalNavigation component
  Backpack-SwiftUI/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
  Backpack-SwiftUI/HorizontalNavigation/README.md
  Backpack-SwiftUI/Tests/HorizontalNavigation/BPKHorizontalNavigationTests.swift
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_defaultSize.dark-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_defaultSize.light-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_defaultSize.rtl.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_smallSize.dark-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_smallSize.light-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithIcon_smallSize.rtl.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_defaultSize.dark-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_defaultSize.light-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_defaultSize.rtl.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_smallSize.dark-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_smallSize.light-mode.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_allTabsWithoutIcon_smallSize.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/HorizontalNavigation/HorizontalNavigationExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_horizontal-navigation___default_dm.png
  screenshots/iPhone-swiftui_horizontal-navigation___default_lm.png
Labels: swiftui, minor, new-component

#1938 Refactor BPKHorizontalNavigation to include onClick handlers for tab selection
  Backpack-SwiftUI/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
  Backpack-SwiftUI/HorizontalNavigation/README.md
  Backpack-SwiftUI/Tests/HorizontalNavigation/BPKHorizontalNavigationTests.swift
  Example/Backpack/SwiftUI/Components/HorizontalNavigation/HorizontalNavigationExampleView.swift
Labels: swiftui, minor

#1941 Re-enable light/dark mode switching on the example app
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack/SceneDelegate.swift
  Example/Backpack/Utils/ThemeHelpers.swift
Labels: skip-changelog

#1942 ACC-459 BottomSheet close button
  Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetHeader.swift
  Backpack-SwiftUI/Button/Classes/BPKCloseButton.swift
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withError.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withError.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.rtl.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader.rtl.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleClosable.light-mode.png
  Backpack-SwiftUI/Tests/BottomSheet/__Snapshots__/BPKBottomSheetTests/test_bottomSheetHeader_titleClosable.rtl.png
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
Labels: patch, Accessibility

#1922 Improve AppSearchModal tap indication
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
  Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContent.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentInputStateClear.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsCustomText.rtl.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withContentWhenPrefixIsIcon.rtl.png
  Example/Backpack/SwiftUI/Components/AppSearchModal/AppSearchModalExampleView.swift
Labels: minor, Accessibility

#1934 DON-335: Add accessibility identifiers to PlaceSelector elements
  Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
Labels: minor, Accessibility

#1948 Refactor BPKImageGalleryImageGridStyle to use structs for chip and image categories
  Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryGrid.swift
  Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryImageGridStyle.swift
  Example/Backpack/SwiftUI/Components/ImageGalleryGridView/ImageGalleryGridExampleView.swift
Labels: swiftui, major

#1950 Update Xcode version to 14.2 in GitHub Actions workflow for Releases
  .github/workflows/release.yml
Labels: patch
