Repository Skyscanner/backpack-ios, pull requests merged in 2024-06, with the labels that each got.

#1975 ACC-460 SwiftUI button font scaling
  Backpack-SwiftUI/Button/Classes/BPKButton.swift
  Backpack-SwiftUI/Button/Classes/CurrentStateButtonStyle.swift
  Backpack-SwiftUI/Tests/Button/BPKButtonTests.swift
  Backpack-SwiftUI/Tests/Button/__Snapshots__/BPKButtonTests/testAccessibilityDynamicType.a11y.png
  Example/Backpack/SwiftUI/Components/Button/ButtonsExampleView.swift
Labels: patch, Accessibility

#1973 Allow BPKText to receive a Text object
  Backpack-SwiftUI/Tests/Text/BPKTextTests.swift
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKTextTests/test_textWithTextView.dark-mode.png
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKTextTests/test_textWithTextView.light-mode.png
  Backpack-SwiftUI/Tests/Text/__Snapshots__/BPKTextTests/test_textWithTextView.rtl.png
  Backpack-SwiftUI/Text/Classes/BPKText.swift
  Backpack-SwiftUI/Text/README.md
Labels: swiftui, minor

#1978 Update iOS deployment targets to 16.0
  Backpack-Common.podspec
  Backpack-Fonts/Backpack-Fonts.podspec
  Backpack-SwiftUI.podspec
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContentView.swift
  Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift
  Backpack.podspec
  Backpack/Backpack.h
  Backpack/Button/Classes/BPKButton.m
  Backpack/Button/Classes/BPKLegacyLinkButton.m
  Backpack/Card/Classes/BPKCardDivider.m
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/DarkMode/Classes/DarkMode.h
  Backpack/DarkMode/README.md
  Backpack/NavigationBar/Classes/BPKNavigationBar.m
  Example/Backpack Screenshot/SnapshotHelper.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
  Example/Backpack/UIKit/Components/Button/BPKButtonsViewController.m
  Example/Backpack/Utils/ThemeHelpers.swift
  Example/Podfile
  Example/Podfile.lock
  templates/BPKColor.m.njk
Labels: major

#1980 Revert "Update iOS deployment targets to 16.0"
  Backpack-Common.podspec
  Backpack-Fonts/Backpack-Fonts.podspec
  Backpack-SwiftUI.podspec
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/Legacy/LegacyBottomSheetContentView.swift
  Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift
  Backpack.podspec
  Backpack/Backpack.h
  Backpack/Button/Classes/BPKButton.m
  Backpack/Button/Classes/BPKLegacyLinkButton.m
  Backpack/Card/Classes/BPKCardDivider.m
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/DarkMode/Classes/DarkMode.h
  Backpack/DarkMode/README.md
  Backpack/NavigationBar/Classes/BPKNavigationBar.m
  Example/Backpack Screenshot/SnapshotHelper.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
  Example/Backpack/UIKit/Components/Button/BPKButtonsViewController.m
  Example/Backpack/Utils/ThemeHelpers.swift
  Example/Podfile
  Example/Podfile.lock
  templates/BPKColor.m.njk
Labels: skip-changelog

#1981 Card Button in SwiftUI
  Backpack-SwiftUI/CardButton/Classes/BPKCardButtonSize.swift
  Backpack-SwiftUI/CardButton/Classes/BPKCardButtonStyle.swift
  Backpack-SwiftUI/CardButton/Classes/BPKSaveCardButton.swift
  Backpack-SwiftUI/CardButton/Classes/BPKShareCardButton.swift
  Backpack-SwiftUI/CardButton/README.md
  Backpack-SwiftUI/Tests/CardButton/BPKSaveCardButtonTests.swift
  Backpack-SwiftUI/Tests/CardButton/BPKShareCardButtonTests.swift
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKSaveCardButtonTests/test_allCases.dark-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKSaveCardButtonTests/test_allCases.light-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKSaveCardButtonTests/test_allCases.rtl.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsFalse.dark-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsFalse.light-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsFalse.rtl.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsTrue.dark-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsTrue.light-mode.png
  Backpack-SwiftUI/Tests/CardButton/__Snapshots__/BPKShareCardButtonTests/test_whenCheckedIsTrue.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Card Button/CardButtonExampleView.swift
  Example/Backpack/UIKit/Components/Card/Card Button/CardButtonsViewController.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-card-button___all_dm.png
  screenshots/iPhone-card-button___all_lm.png
  screenshots/iPhone-swiftui_card-button___all_dm.png
  screenshots/iPhone-swiftui_card-button___all_lm.png
Labels: minor

#1987 DON-386: Add accessibility support to BPKNudger
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift
Labels: minor, Accessibility

#1997 [PAN-3170] Fixed nudger component subtitle display without wrap case of long string
  Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
  Backpack-SwiftUI/Tests/Nudger/BPKNudgerTests.swift
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_dynamic_type_on_title_and_subtitle.a11y.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_long_subtitle.dark-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_long_subtitle.light-mode.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_title_and_long_subtitle.rtl.png
  Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift
  screenshots/iPhone-swiftui_nudger___default_dm.png
  screenshots/iPhone-swiftui_nudger___default_lm.png
Labels: minor, bpk

#1979 Integrate TTTAttributedLabel
  Backpack.podspec
  Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
  Backpack/TappableLinkLabel/Classes/TTTAttributedLabel/TTTAttributedLabel.h
  Backpack/TappableLinkLabel/Classes/TTTAttributedLabel/TTTAttributedLabel.m
  Example/Podfile.lock
Labels: patch
