Repository Skyscanner/backpack-ios, pull requests merged in 2024-07, with the labels that each got.

#2000 RALP-4865 Use ubuntu-22.04 instead of ubuntu-latest
  .github/workflows/_test.yml
  .github/workflows/label-check.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: skip-changelog

#2001 AI-600: Fix TextArea frame
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_defaultSettings.rtl.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_emptyArea.rtl.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.dark-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.light-mode.png
  Backpack-SwiftUI/Tests/TextArea/__Snapshots__/BPKTextAreaTests/test_withPlaceholder.rtl.png
  Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift
Labels: swiftui, minor

#2004 OGM-2630: Fix letter cut in german
  Backpack/Button/Classes/BPKButton.m
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultDestructive.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultDestructive.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultDestructive.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultFeatured.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultFeatured.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultFeatured.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLink.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLink.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLink.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLinkOnDark.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLinkOnDark.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultLinkOnDark.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimary.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimary.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimary.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnDark.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnDark.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnDark.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnLight.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnLight.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultPrimaryOnLight.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondary.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondary.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondary.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondaryOnDark.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondaryOnDark.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKButtonSnapshotTests/testDefaultSecondaryOnDark.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithWholeMonthButton.rtl.png
Labels: minor

#2003 [Panda] PAN-3180: BpkPrice component update style
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_large_withTrailingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withTrailingAlignment.rtl.png
Labels: swiftui, minor, bpk

#2013 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-changelog

#2011 [Panda]PAN-2774: Fix Incorrect month format in calendar view
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
Labels: minor

#2009 OGM-2610: added icon in calendar
  Backpack/Calendar/Classes/BPKCalendarPriceLabelCell.m
  Backpack/Calendar/Classes/BPKCalendarPriceLabelCellData.h
  Backpack/Calendar/Classes/BPKCalendarPriceLabelCellData.m
  Backpack/Calendar/Classes/BPKCalendarPriceLabelStyle.h
  Backpack/Calendar/Classes/BPKCalendarPriceLabelStyle.m
  Backpack/Tests/SnapshotTests/BPKCalendarSnapshotTest.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithPriceLabels.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithPriceLabels.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKCalendarSnapshotTest/testCalendarWithPriceLabels.rtl.png
  Example/Backpack/UIKit/Components/Calendar/CalendarViewController.swift
Labels: minor

#2016 Make medium bottom sheet expansion configurable
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheetContentMode.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
Labels: swiftui, minor

#2012 [ChAI] [AI-642]: Create CarouselCard Component
  Backpack-SwiftUI/CarouselCard/Classes/BPKCarouselCard.swift
  Backpack-SwiftUI/CarouselCard/README.md
  Backpack-SwiftUI/Tests/CarouselCard/BPKCarouselCardTests.swift
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.dark-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.light-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.rtl.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/test_accessibility.a11y.png
  Example/Backpack Screenshot/Screenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/CarouselCard/CarouselCardExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-carousel-card__default_dm.png
  screenshots/iPhone-carousel-card__default_lm.png
Labels: minor

#2020 Updating snapshots after macos update
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withError.dark-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withError.light-mode.png
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withError.rtl.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.dark-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.light-mode.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/testCarouselCard.rtl.png
  Backpack-SwiftUI/Tests/CarouselCard/__Snapshots__/BPKCarouselCardTests/test_accessibility.a11y.png
Labels: patch

#2017 [DO NOT MERGE] Add peeking bottom sheet functionality
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
  Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift
Labels: swiftui, minor

#2021 No-Jira: Update BPKIconView to adapt its size according to dynamic type
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.a11y.png
  Backpack-SwiftUI/Tests/HorizontalNavigation/__Snapshots__/BPKHorizontalNavigationTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/Nudger/__Snapshots__/BPKNudgerTests/test_dynamic_type_on_title_and_subtitle.a11y.png
  Backpack-SwiftUI/Tests/SearchInputSummary/__Snapshots__/BPKSearchInputSummaryTests/test_accessibility.a11y.png
Labels: swiftui, minor

#2029 SwiftUI DynamicType toggle
  Backpack-SwiftUI/Button/Classes/BPKButton.swift
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
  Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
  Backpack-SwiftUI/Text/Classes/BPKText.swift
  Backpack-SwiftUI/TextField/Classes/BPKTextField.swift
Labels: patch

#2028 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-changelog

#2030 Add original copyright to files ported from external libraries
  Backpack/Calendar/Classes/FSCalendar/FSCalendar.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendar.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarAppearance.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarAppearance.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCalculator.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCalculator.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCell.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCell.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCollectionView.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCollectionView.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCollectionViewLayout.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarCollectionViewLayout.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarConstants.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarConstants.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarDelegationFactory.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarDelegationFactory.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarDelegationProxy.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarDelegationProxy.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarDynamicHeader.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarExtensions.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarExtensions.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarHeaderView.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarHeaderView.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarSeparatorDecorationView.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarSeparatorDecorationView.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarStickyHeader.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarStickyHeader.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarTransitionCoordinator.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarTransitionCoordinator.m
  Backpack/Calendar/Classes/FSCalendar/FSCalendarWeekdayView.h
  Backpack/Calendar/Classes/FSCalendar/FSCalendarWeekdayView.m
  Backpack/Toast/Classes/MBProgressHUD.h
  Backpack/Toast/Classes/MBProgressHUD.m
Labels: patch
