Repository Skyscanner/backpack-ios, pull requests merged in 2024-02, with the labels that each got.

#1876 ACC-367 Update BPKTabBar(Item)
  Backpack/Backpack.h
  Backpack/TabBarController/Classes/BPKTabBarController.h
  Backpack/TabBarController/Classes/BPKTabBarController.m
  Backpack/TabBarController/Classes/BPKTabBarController.swift
  Backpack/TabBarController/Classes/BPKTabBarDotImageDefinition.h
  Backpack/TabBarController/Classes/BPKTabBarDotImageDefinition.swift
  Backpack/TabBarController/Classes/BPKTabBarItem.h
  Backpack/TabBarController/Classes/BPKTabBarItem.m
  Backpack/TabBarController/Classes/BPKTabBarItem.swift
  Backpack/TabBarController/Classes/TabBarController.h
  Backpack/Tests/SnapshotTests/BPKTabBarControllerSnapshotTest.swift
  Backpack/Tests/UnitTests/BPKTabBarControllerTest.m
  Backpack/Tests/UnitTests/BPKTabBarItemTest.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/Images.xcassets/Tab/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_home.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_home.imageset/day_home.svg
  Example/Backpack/Images.xcassets/Tab/tab_home_selected.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_home_selected.imageset/day_selected_home.svg
  Example/Backpack/Images.xcassets/Tab/tab_profile.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_profile.imageset/day_profile.svg
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_dm.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_dm.imageset/night_profile_notification.svg
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_lm.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_lm.imageset/day_profile_notification.svg
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_selected.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_profile_dot_selected.imageset/day_selected_profile_notification.svg
  Example/Backpack/Images.xcassets/Tab/tab_profile_selected.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_profile_selected.imageset/day_selected_profile.svg
  Example/Backpack/Images.xcassets/Tab/tab_search.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_search.imageset/day_explore.svg
  Example/Backpack/Images.xcassets/Tab/tab_search_selected.imageset/Contents.json
  Example/Backpack/Images.xcassets/Tab/tab_search_selected.imageset/day_selected_explore.svg
  Example/Backpack/Images.xcassets/tab_explore_with_dot_dm.imageset/Contents.json
  Example/Backpack/Images.xcassets/tab_explore_with_dot_dm.imageset/ic_explore_dot_deselected_darkmode.pdf
  Example/Backpack/Images.xcassets/tab_explore_with_dot_lm.imageset/Contents.json
  Example/Backpack/Images.xcassets/tab_explore_with_dot_lm.imageset/ic_explore_dot_deselected_lightmode.pdf
  Example/Backpack/Images.xcassets/tab_profile_with_dot_dm.imageset/Contents.json
  Example/Backpack/Images.xcassets/tab_profile_with_dot_dm.imageset/ic_profile_dot_deselected_darkmode.pdf
  Example/Backpack/Images.xcassets/tab_profile_with_dot_lm.imageset/Contents.json
  Example/Backpack/Images.xcassets/tab_profile_with_dot_lm.imageset/ic_profile_dot_deselected_lightmode.pdf
  Example/Backpack/UIKit/Components/Tab bar/TabBarControllerStoryViewController.swift
  Example/Backpack/Utils/FeatureStories/TabsViewController.swift
  screenshots/iPhone SE (3rd generation)-tab-bar-controller___default_dm.png
  screenshots/iPhone SE (3rd generation)-tab-bar-controller___default_lm.png
Labels: minor, Accessibility

#1883 BPKAppSearchModal, zoom
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
  Example/Podfile.lock
Labels: patch, Accessibility

#1884 Update card list screenshots
  Example/Backpack/Utils/FeatureStories/Groups/CardListGroups.swift
  screenshots/iPhone-swiftui_card-list___rail-12-elements-with-section-header-button_dm.png
  screenshots/iPhone-swiftui_card-list___rail-12-elements-with-section-header-button_lm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand-with-section-header-button_dm.png
  screenshots/iPhone-swiftui_card-list___stack-accessory-expand-with-section-header-button_lm.png
Labels: minor

#1886 [DON-385] Set line limit in `SearchAppModalContentView` cell's subtitle
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
Labels: minor
