Repository Skyscanner/backpack-ios, pull requests merged in 2024-03, with the labels that each got.

#1894 BPKPrice support row alignment
  Backpack-SwiftUI/Price/Classes/BPKPrice.swift
  Backpack-SwiftUI/Tests/Price/PriceTests.swift
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withLeadingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withRowAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_extraSmall_withTrailingAlignment.rtl.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.dark-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.light-mode.png
  Backpack-SwiftUI/Tests/Price/__Snapshots__/PriceTests/test_small_withRowAlignment.rtl.png
  Example/Backpack/SwiftUI/Components/Price/PriceExampleView.swift
  screenshots/iPhone-swiftui_price___extraSmall_dm.png
  screenshots/iPhone-swiftui_price___extraSmall_lm.png
  screenshots/iPhone-swiftui_price___large_dm.png
  screenshots/iPhone-swiftui_price___large_lm.png
  screenshots/iPhone-swiftui_price___small_dm.png
  screenshots/iPhone-swiftui_price___small_lm.png
Labels: minor

#1890 Add NavBar component and tests
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView+Style.swift
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationViewItem.swift
  Backpack-SwiftUI/NavigationBar/README.md
  Backpack-SwiftUI/Tests/NavBar/BPKNavigationViewTests.swift
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_default.dark-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_default.light-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_default.rtl.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_surfaceContrast.dark-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_surfaceContrast.light-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_surfaceContrast.rtl.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_transparent.dark-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_transparent.light-mode.png
  Backpack-SwiftUI/Tests/NavBar/__Snapshots__/BPKNavigationViewTests/test_transparent.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/NavBar/NavBarExampleVIew.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_navbar___default_dm.png
  screenshots/iPhone-swiftui_navbar___default_lm.png
  screenshots/iPhone-swiftui_navbar___surfaceContrast_dm.png
  screenshots/iPhone-swiftui_navbar___surfaceContrast_lm.png
  screenshots/iPhone-swiftui_navbar___transparent_dm.png
  screenshots/iPhone-swiftui_navbar___transparent_lm.png
Labels: swiftui, minor, new-component

#1899 Update SwiftUIScreenshots.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
Labels: skip-changelog

#1893 [LMN-844] Add BPKRatingBar SwiftUI component
  Backpack-SwiftUI/RatingBar/Classes/BPKRatingBar+Scale.swift
  Backpack-SwiftUI/RatingBar/Classes/BPKRatingBar+Style.swift
  Backpack-SwiftUI/RatingBar/Classes/BPKRatingBar.swift
  Backpack-SwiftUI/RatingBar/README.md
  Backpack-SwiftUI/Tests/RatingBar/BPKRatingBarTests.swift
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_aboveScale.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_aboveScale.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_aboveScale.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_belowZero.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_belowZero.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_belowZero.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_defaultStyleZeroToFive.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_defaultStyleZeroToFive.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_defaultStyleZeroToFive.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_noScale.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_noScale.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_noScale.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_onContrastStyle.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_onContrastStyle.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_onContrastStyle.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingEmpty.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingEmpty.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingEmpty.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingFull.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingFull.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_ratingFull.rtl.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_zeroToTen.dark-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_zeroToTen.light-mode.png
  Backpack-SwiftUI/Tests/RatingBar/__Snapshots__/BPKRatingBarTests/test_zeroToTen.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/RatingBar/RatingBarExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  package-lock.json
  package.json
  screenshots/iPhone-swiftui_rating-bar___default_dm.png
  screenshots/iPhone-swiftui_rating-bar___default_lm.png
Labels: swiftui, minor, new-component

#1902 Fix SwiftUI.BPKShimmer not working in iOS 17
  Backpack-SwiftUI/Skeleton/Classes/BPKShimmer.swift
  Backpack-SwiftUI/Tests/AppSearchModal/__Snapshots__/BPKAppSearchModalTests/test_withLoading.rtl.png
Labels: minor

#1901 Create BPKImageGalleryPreview component
  Backpack-Common/Carousel/Classes/BPKInternalCarousel.swift
  Backpack-SwiftUI/Carousel/Classes/BPKCarousel.swift
  Backpack-SwiftUI/ImageGalleryPreview/Classes/BPKImageGalleryPreview.swift
  Backpack-SwiftUI/ImageGalleryPreview/README.md
  Backpack-SwiftUI/Tests/ImageGalleryPreview/BPKImageGalleryPreviewTests.swift
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.dark-mode.png
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.light-mode.png
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.rtl.png
  Backpack/Carousel/Classes/BPKCarousel.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/ImageGalleryPreview/ImageGalleryPreviewExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_image-gallery-preview___default_dm.png
  screenshots/iPhone-swiftui_image-gallery-preview___default_lm.png
Labels: swiftui, minor, new-component

#1904 Fixing scrolling issue and cleanup
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView+Style.swift
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
  Backpack-SwiftUI/NavigationBar/Classes/CollapsedNavigationBar.swift
  Backpack-SwiftUI/NavigationBar/Classes/ExpandedNavigationBar.swift
  Backpack-SwiftUI/NavigationBar/Classes/NavBarScrollViewWithOffset.swift
  Backpack-SwiftUI/Tests/NavBar/BPKNavigationViewTests.swift
Labels: patch

#1908 Refactor BPKNavigationView to support transparent style better
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView+Style.swift
  Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
  Backpack-SwiftUI/NavigationBar/Classes/ObservableScrollView.swift
Labels: patch

#1911 LMN-1303 Dismiss Keyboard on Scrolling, and disable auto-correct for Place Selector
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
  Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
  Backpack-SwiftUI/Utils/Classes/ObservableScrollView.swift
Labels: patch

#1916 sonic/nojira fix floating notification's action button background color in dark modew
  Backpack/FloatingNotification/Classes/FloatingNotificationView.swift
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithLongTextIconAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextAndButtonForiPad.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButton.rtl.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.dark-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.light-mode.png
  Backpack/Tests/SnapshotTests/__Snapshots__/BPKFloatingNotificationSnapshotTests/testViewSnapshotWithTextIconAndButtonForiPad.rtl.png
Labels: minor

#1912 Add BPKImageGallerySlideshow component
  Backpack-Common/Carousel/Classes/BPKInternalCarousel.swift
  Backpack-SwiftUI/Carousel/Classes/BPKCarousel.swift
  Backpack-SwiftUI/ImageGalleryPreview/Classes/BPKImageGalleryPreview.swift
  Backpack-SwiftUI/ImageGallerySlideshow/Classes/BPKImageGalleryImage.swift
  Backpack-SwiftUI/ImageGallerySlideshow/Classes/BPKImageGallerySlideshow.swift
  Backpack-SwiftUI/ImageGallerySlideshow/README.md
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.dark-mode.png
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.light-mode.png
  Backpack-SwiftUI/Tests/ImageGalleryPreview/__Snapshots__/BPKImageGalleryPreviewTests/test_imageGalleryPreview.rtl.png
  Backpack-SwiftUI/Tests/ImageGallerySlideshow/BPKImageGallerySlideshowTests.swift
  Backpack-SwiftUI/Tests/ImageGallerySlideshow/__Snapshots__/BPKImageGallerySlideshowTests/test_imageGalleryPreview.dark-mode.png
  Backpack-SwiftUI/Tests/ImageGallerySlideshow/__Snapshots__/BPKImageGallerySlideshowTests/test_imageGalleryPreview.light-mode.png
  Backpack-SwiftUI/Tests/ImageGallerySlideshow/__Snapshots__/BPKImageGallerySlideshowTests/test_imageGalleryPreview.rtl.png
  Backpack/Carousel/Classes/BPKCarousel.swift
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/ImageGallerySlideshow/ImageGallerySlideshowExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_image-gallery-slideshow___default_dm.png
  screenshots/iPhone-swiftui_image-gallery-slideshow___default_lm.png
Labels: swiftui, minor, new-component

#1918 feat: introduce a11y snapshots
  Backpack-SwiftUI/Tests/Badge/BPKBadgeTests.swift
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.a11y.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.dark-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.light-mode.png
  Backpack-SwiftUI/Tests/Badge/__Snapshots__/BPKBadgeTests/test_badgeWillKeepSingleLine.rtl.png
  Backpack-SwiftUI/Tests/SnapshotHelpers/SnapshotHelpers.swift
Labels: skip-changelog, Accessibility

#1919 ACC-453 / ACC-454 AppSearchModal accessibility fix
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
  Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
Labels: patch, Accessibility

#1920 fix: Move content shape to HSTack to allow custom button to be tappable
  Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
Labels: patch, Accessibility
