Repository Skyscanner/backpack-ios, pull requests merged in 2025-02, with the labels that each got.

#2146 DON-1068: Add floating year label configuration to BPKCalendar
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
  Backpack-SwiftUI/Calendar/README.md
  Backpack-SwiftUI/Tests/Calendar/BPKCalendarTests.swift
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.rtl.png
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleRangeView.swift
  Example/Backpack/Utils/FeatureStories/Groups/CalendarGroups.swift
Labels: swiftui, minor, bpk

#2167 Refactor calendar components to use CalendarGridCalculator for improved performance
  .github/workflows/_test.yml
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarGridCalculator.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarMonthGrid.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
  Backpack-SwiftUI/Tests/Calendar/CalendarGridCalculatorTests.swift
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.rtl.png
  Example/Podfile.lock
  Gemfile.lock
Labels: minor

#2166 DON-1067: Change calendar selection behaviour
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarSelectionHandler.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarSelectionHandler.swift
  Backpack-SwiftUI/Calendar/README.md
  Example/Backpack.xcodeproj/project.pbxproj
Labels: swiftui, minor

#2169 DON-1089: Scroll issue
  Backpack-SwiftUI/Calendar/Classes/CalendarDayCells/DefaultCalendarDayCell.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarMonthGrid.swift
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_differentMonth.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameDay.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_sameMonth.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_rangeSelectionCalendar_withAccessoryView.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendar.rtl.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.dark-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.light-mode.png
  Backpack-SwiftUI/Tests/Calendar/__Snapshots__/BPKCalendarTests/test_singleSelectionCalendarWithNoFloatYearLabel.rtl.png
Labels: minor

#2178 DON-1170 Remove extra action from segmentedControl when tapped on selected tab
  Backpack-SwiftUI/SegmentedControl/Classes/BPKSegmentedControl.swift
  Backpack-SwiftUI/Tests/SegmentedControl/__Snapshots__/BPKSegmentedControlTests/test_firstSegmentSelected.dark-mode.png
Labels: minor
