Repository Skyscanner/backpack-ios, pull requests merged in 2025-01, with the labels that each got.

#2128 DON-1019: Fix BPKCalendar internal containers
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
  Backpack-SwiftUI/Calendar/Classes/CalendarDayCells/CalendarSelectableCell.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarMonthGrid.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
  Backpack-SwiftUI/Calendar/Classes/Core/EmptyCellInfo.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeDayAccessibilityProvider.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleDayAccessibilityProvider.swift
  Backpack-SwiftUI/Tests/Calendar/BPKCalendarTests.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleRangeView.swift
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleSingleView.swift
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleWholeMonthView.swift
  Example/Podfile.lock
Labels: swiftui, minor

#2130 Refactor calendar to support dynamic selection type changes
  Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
  Backpack-SwiftUI/Calendar/Classes/CalendarDayCells/CalendarSelectableCell.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarMonthGrid.swift
  Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
  Backpack-SwiftUI/Calendar/Classes/Core/EmptyCellInfo.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Range/RangeDayAccessibilityProvider.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
  Backpack-SwiftUI/Calendar/Classes/Single/SingleDayAccessibilityProvider.swift
  Backpack-SwiftUI/Tests/Calendar/BPKCalendarTests.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleDynamicView.swift
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleRangeView.swift
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleSingleView.swift
  Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleWholeMonthView.swift
  Example/Backpack/Utils/FeatureStories/Groups/CalendarGroups.swift
Labels: minor

#2131 Fix drag direction issue in BPKSlider for RTL layouts
  Backpack-SwiftUI/Slider/Classes/BPKRangeSlider.swift
  Backpack-SwiftUI/Slider/Classes/BPKSlider.swift
  Backpack-SwiftUI/Slider/Classes/BPKSliderHelpers.swift
  Backpack-SwiftUI/Tests/Slider/SliderTests.swift
  Example/Backpack.xcodeproj/project.pbxproj
Labels: minor

#2132 [TEMPURA-2186] Custom icons support
  Backpack-SwiftUI/Icons/Classes/BPKIcon.swift
  Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  Backpack-SwiftUI/Tests/Icons/BPKIconViewTests.swift
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomLargeIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomLargeIcon.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomLargeIcon.rtl.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomSmallIcon.dark-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomSmallIcon.light-mode.png
  Backpack-SwiftUI/Tests/Icons/__Snapshots__/BPKIconViewTests/testCustomSmallIcon.rtl.png
  Backpack-SwiftUI/Tests/Images.xcassets/custom-icon-lg.imageset/Contents.json
  Backpack-SwiftUI/Tests/Images.xcassets/custom-icon-lg.imageset/custom-icon-lg.svg
  Backpack-SwiftUI/Tests/Images.xcassets/custom-icon-sm.imageset/Contents.json
  Backpack-SwiftUI/Tests/Images.xcassets/custom-icon-sm.imageset/custom-icon-sm.svg
  templates/swiftui/BPKIcons.njk
Labels: minor

#2134 TEMPURA-2186: Create separate method for custom icons
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  templates/swiftui/BPKIcons.njk
Labels: minor

#2142 Make bundle parameter optional in BPKIcon methods
  Backpack-SwiftUI/Icons/Classes/BPKIcon.swift
  Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
  templates/swiftui/BPKIcons.njk
Labels: minor

#2153 Ralp/remove ios 15 support
  Backpack-Common.podspec
  Backpack-Fonts/Backpack-Fonts.podspec
  Backpack-SwiftUI.podspec
  Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
  Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
  Backpack-SwiftUI/GraphicPromo/Classes/BPKGraphicPromo.swift
  Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift
  Backpack.podspec
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Podfile
Labels: major

#2154 [NO JIRA]: Updating foundations to the latest
  Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  Backpack/Color/Classes/Generated/BPKColor.h
  Backpack/Color/Classes/Generated/BPKColor.m
  Backpack/Color/Classes/Generated/UIColor+Backpack.h
  package-lock.json
  package.json
Labels: patch

#2141 DON-1029 segmented control custom
  Backpack-SwiftUI/SegmentedControl/Classes/BPKSegmentedControl.swift
  Backpack-SwiftUI/SegmentedControl/README.md
  Backpack-SwiftUI/Tests/SegmentedControl/BPKSegmentedControlTests.swift
  Backpack-SwiftUI/Tests/SegmentedControl/__Snapshots__/BPKSegmentedControlTests/test_accessibility.a11y.png
  Backpack-SwiftUI/Tests/SegmentedControl/__Snapshots__/BPKSegmentedControlTests/test_firstSegmentSelected.dark-mode.png
  Backpack-SwiftUI/Tests/SegmentedControl/__Snapshots__/BPKSegmentedControlTests/test_firstSegmentSelected.light-mode.png
  Backpack-SwiftUI/Tests/SegmentedControl/__Snapshots__/BPKSegmentedControlTests/test_firstSegmentSelected.rtl.png
  Example/Backpack Screenshot/SwiftUIScreenshots.swift
  Example/Backpack.xcodeproj/project.pbxproj
  Example/Backpack/SwiftUI/Components/SegmentedControl/SegmentedControlExampleView.swift
  Example/Backpack/Utils/FeatureStories/ComponentCells.swift
  screenshots/iPhone-swiftui_segmented-control___default_dm.png
  screenshots/iPhone-swiftui_segmented-control___default_lm.png
Labels: swiftui, major, bpk, new-component

#2157 SDPLAT-26630: use github app in workflows
  .github/workflows/_build.yml
  .github/workflows/_test.yml
  .github/workflows/label-check.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: skip-changelog
